/**
 * init command - Initialize transpec in project
 */

import chalk from 'chalk';
import * as fs from 'fs/promises';
import * as path from 'path';
import { frameworkRegistry } from '../../core/framework/index.js';
import { Logger, LogModules, LogLevel, getLogger } from '../../core/logging/index.js';

const logger = getLogger(LogModules.CLI);

export interface InitOptions {
  source?: string;
  target?: string;
  ide?: string;
  mode?: string;
  verbose?: boolean;
}

export async function initCommand(options: InitOptions) {
  // Configure logging
  Logger.configure({
    level: options.verbose ? LogLevel.DEBUG : LogLevel.INFO,
    console: true,
  });

  logger.info('Starting transpec initialization');
  const projectPath = process.cwd();

  console.log(chalk.blue('\nInitializing transpec...\n'));

  try {
    // Detect frameworks
    logger.debug('Detecting frameworks in project', { path: projectPath });
    const detected = await frameworkRegistry.detect(projectPath);
    logger.debug('Detection completed', { detected: detected.length });

    if (detected.length === 0) {
      console.log(chalk.yellow('No frameworks detected in current project.'));
      console.log('Please ensure you are in a project with OpenSpec, Trellis, or other supported frameworks.\n');
      logger.warn('No frameworks found during detection');
      process.exit(1);
    }

    console.log(chalk.green(`Detected frameworks: ${detected.map(d => d.framework).join(', ')}\n`));
    logger.info('Frameworks detected', {
      frameworks: detected.map(d => d.framework),
      entityCounts: detected.map(d => d.entityCount)
    });

    // Use detected framework as source if not specified
    const sourceFramework = options.source || detected[0].framework;
    const targetFramework = options.target || (sourceFramework === 'openspec' ? 'trellis' : 'openspec');
    const mode = options.mode || 'on-demand';
    const ide = options.ide || 'claude-code';

    logger.debug('Configuration determined', { sourceFramework, targetFramework, mode, ide });

    // Validate frameworks
    const sourceAdapter = frameworkRegistry.get(sourceFramework as any);
    const targetAdapter = frameworkRegistry.get(targetFramework as any);

    if (!sourceAdapter) {
      console.error(chalk.red(`Source framework '${sourceFramework}' not supported.`));
      console.log('Supported:', frameworkRegistry.getSupportedFrameworks().join(', '));
      logger.error('Unsupported source framework', { framework: sourceFramework });
      process.exit(1);
    }

    if (!targetAdapter) {
      console.error(chalk.red(`Target framework '${targetFramework}' not supported.`));
      console.log('Supported:', frameworkRegistry.getSupportedFrameworks().join(', '));
      logger.error('Unsupported target framework', { framework: targetFramework });
      process.exit(1);
    }

    if (sourceFramework === targetFramework) {
      console.error(chalk.red('Source and target frameworks must be different.'));
      logger.error('Source and target are the same', { framework: sourceFramework });
      process.exit(1);
    }

    // Create .transpec directory
    const transpecDir = path.join(projectPath, '.transpec');
    logger.debug('Creating .transpec directory', { path: transpecDir });
    await fs.mkdir(transpecDir, { recursive: true });

    // Create config
    const createdAt = new Date().toISOString();
    const config = {
      version: '1.0.0',
      project: {
        sourceFramework,
        targetFramework,
        ide,
        mode,
      },
      logging: {
        level: options.verbose ? 'debug' : 'info',
        console: true,
        file: {
          enabled: false,
        },
      },
      createdAt,
    };

    const configYaml = `# Transpec Configuration
# Generated by transpec init

version: "1.0.0"

project:
  sourceFramework: ${sourceFramework}
  targetFramework: ${targetFramework}
  ide: ${ide}
  mode: ${mode}

logging:
  level: ${options.verbose ? 'debug' : 'info'}
  console: true
  file:
    enabled: false

createdAt: "${createdAt}"
`;

    await fs.writeFile(path.join(transpecDir, 'config.yaml'), configYaml);
    logger.debug('Config written', { path: path.join(transpecDir, 'config.yaml') });

    // Create workspace directory
    await fs.mkdir(path.join(transpecDir, 'workspace'), { recursive: true });
    await fs.mkdir(path.join(transpecDir, 'ir'), { recursive: true });
    await fs.mkdir(path.join(transpecDir, 'logs'), { recursive: true });
    logger.debug('Directory structure created');

    console.log(chalk.green('Transpec initialized successfully!\n'));
    console.log(chalk.bold('Configuration:'));
    console.log(`  Source: ${chalk.cyan(sourceFramework)}`);
    console.log(`  Target: ${chalk.cyan(targetFramework)}`);
    console.log(`  IDE: ${chalk.cyan(ide)}`);
    console.log(`  Mode: ${chalk.cyan(mode)}`);
    console.log(`\nTo start conversion, run: ${chalk.bold('transpec convert')}\n`);

    logger.info('Initialization complete', {
      sourceFramework,
      targetFramework,
      ide,
      mode
    });

  } catch (error) {
    logger.error('Initialization failed', { error: (error as Error).message, stack: (error as Error).stack });
    console.error(chalk.red('Error initializing transpec:'), error);
    process.exit(1);
  }
}
