import * as fs from 'fs/promises';
import * as path from 'path';
import {
  getProjectEnhancedAnalysisPath,
  getProjectPostprocessContextPath,
  getProjectPreprocessContextPath,
  toProjectRelativePath,
} from '../skill/paths.js';
import type {
  EnhancedAnalysisFile,
  PostprocessContextFile,
  PreprocessContextFile,
} from '../skill/project-runtime.js';
import { hasCliSignals, hasUiSignals } from '../framework/task-signals.js';

const SKIPPED_SCAN_DIRECTORIES = new Set([
  '.git',
  '.trellis',
  '.transpec',
  'build',
  'coverage',
  'dist',
  'node_modules',
  'target',
  'tmp',
]);

export interface GeneratedSpecArtifact {
  layer: 'backend' | 'frontend' | 'guides';
  path: string;
}

export interface PostprocessRunResult {
  generatedFiles: GeneratedSpecArtifact[];
  warnings: string[];
}

interface AnalysisEntity {
  id: string;
  name: string;
  type: string;
  sourcePath: string;
  analysis: EnhancedAnalysisFile['entities'][string] | null;
}

interface RepositoryScanResult {
  extensionCounts: Map<string, number>;
  filesByExtension: Map<string, string[]>;
  topLevelDirectoryCounts: Map<string, number>;
  notableFiles: string[];
}

interface LanguageProfile {
  key: string;
  label: string;
}

const WORKFLOW_BASELINE_MARKER = 'Generated by Transpec as a minimum Trellis runtime skeleton.';
const WORKFLOW_GROUNDED_MARKER = 'Grounded Trellis workflow bootstrap generated by Transpec deterministic postprocess.';
const BACKEND_INDEX_BASELINE_MARKER = 'Generated baseline Trellis backend index.';
const BACKEND_INDEX_GROUNDED_MARKER = 'Grounded Trellis backend index generated by Transpec deterministic postprocess.';
const FRONTEND_INDEX_BASELINE_MARKER = 'Generated baseline Trellis frontend index.';
const FRONTEND_INDEX_GROUNDED_MARKER = 'Grounded Trellis frontend index generated by Transpec deterministic postprocess.';
const GUIDES_INDEX_BASELINE_MARKER = 'Generated baseline Trellis guide index.';
const GUIDES_INDEX_GROUNDED_MARKER = 'Grounded Trellis guide index generated by Transpec deterministic postprocess.';
const GENERATED_GUIDE_MARKER = 'Generated by Transpec deterministic postprocess';

export async function runTargetPostprocess(
  projectPath: string,
  targetFramework: string,
): Promise<PostprocessRunResult> {
  if (targetFramework === 'trellis') {
    return runTrellisPostprocess(projectPath);
  }

  return {
    generatedFiles: [],
    warnings: [`No deterministic postprocess implementation for target framework "${targetFramework}" yet.`],
  };
}

export async function runTrellisPostprocess(projectPath: string): Promise<PostprocessRunResult> {
  const preprocessContext = await readJsonFile<PreprocessContextFile>(getProjectPreprocessContextPath(projectPath));
  const enhancedAnalysis = await readJsonFile<EnhancedAnalysisFile>(getProjectEnhancedAnalysisPath(projectPath));
  const postprocessContext = await readJsonFile<PostprocessContextFile>(getProjectPostprocessContextPath(projectPath));
  const scan = await scanRepository(projectPath);

  const entities = preprocessContext.entities.map(entity => ({
    ...entity,
    analysis: enhancedAnalysis.entities[entity.id] ?? null,
  }));
  const generatedFiles: GeneratedSpecArtifact[] = [];
  const warnings: string[] = [];

  const guidesDir = path.join(projectPath, '.trellis', 'spec', 'guides');
  const backendDir = path.join(projectPath, '.trellis', 'spec', 'backend');
  const frontendDir = path.join(projectPath, '.trellis', 'spec', 'frontend');
  await fs.mkdir(guidesDir, { recursive: true });
  await fs.mkdir(backendDir, { recursive: true });
  await fs.mkdir(frontendDir, { recursive: true });

  const backendArtifact = await writeBackendSpec(projectPath, backendDir, entities, scan);
  generatedFiles.push(backendArtifact);

  const frontendArtifact = await writeFrontendSpec(projectPath, frontendDir, entities, scan);
  if (frontendArtifact) {
    generatedFiles.push(frontendArtifact);
  }

  const guideArtifacts = await writeGuides(
    projectPath,
    guidesDir,
    preprocessContext,
    postprocessContext,
    entities,
    scan,
    generatedFiles,
  );
  generatedFiles.push(...guideArtifacts);

  await writeWorkflowBootstrap(projectPath, scan, generatedFiles);
  await writeBackendIndex(path.join(backendDir, 'index.md'), generatedFiles.filter(file => file.layer === 'backend'), scan);
  await writeFrontendIndex(path.join(frontendDir, 'index.md'), generatedFiles.filter(file => file.layer === 'frontend'), scan);
  await writeGuidesIndex(path.join(guidesDir, 'index.md'), generatedFiles.filter(file => file.layer === 'guides'));

  if (entities.every(entity => !entity.analysis)) {
    warnings.push('Enhanced analysis file did not contain any matching entity IDs; grounded docs were generated from repository scan only.');
  }

  return { generatedFiles, warnings };
}

async function writeBackendSpec(
  projectPath: string,
  backendDir: string,
  entities: AnalysisEntity[],
  scan: RepositoryScanResult,
): Promise<GeneratedSpecArtifact> {
  const specs = entities.filter(entity => entity.type === 'spec');
  const language = detectPrimaryLanguage(scan);
  const repoLooksCli = specs.some(entity => hasCliSignals(
    entity.name,
    entity.sourcePath,
    entity.analysis,
  ))
    || scan.notableFiles.some(file => /cargo\.toml$|package\.json$|main\.(rs|ts|js|py)$/i.test(file));
  const fileName = determineBackendFileName(language, repoLooksCli);
  const filePath = path.join(backendDir, fileName);

  const modulePaths = collectRankedPaths(
    specs.flatMap(entity => entity.analysis?.dependencies ?? []),
    projectPath,
  );
  const aggregatedConstraints = uniqueLimit(
    specs.flatMap(entity => entity.analysis?.constraints ?? []),
    8,
  );

  const content = `# ${determineBackendTitle(language, repoLooksCli)}

> Generated by Transpec deterministic postprocess from repository scan and enhanced analysis.

## Snapshot

- Primary language: ${language.label}
- Runtime shape: ${repoLooksCli ? 'CLI / terminal workflow' : 'repository runtime'}
- Source roots: ${formatInlineList(collectTopRoots(scan))}
- Legacy source specs: \`.trellis/legacy/specs/\`
- Imported historical work: \`.trellis/tasks/archive/\`

## Primary Source Paths

${renderBulletList(modulePaths.length > 0 ? modulePaths.map(file => `\`${file}\``) : ['No code dependency paths were extracted from enhanced analysis.'])}

## Capability Inventory

${renderCapabilitySections(specs, language.label)}

## Cross-Cutting Constraints

${renderBulletList(aggregatedConstraints.length > 0 ? aggregatedConstraints : ['No shared constraints were extracted yet.'])}

## Refresh Triggers

- Re-run \`transpec apply\` after RAW IR or target emission rules change.
- Re-run \`transpec postprocess\` after enhanced analysis or repository structure changes.
- Update this guide when runtime entrypoints or capability ownership move.
`;

  await fs.writeFile(filePath, `${content.trim()}\n`);
  return { layer: 'backend', path: toProjectRelativePath(projectPath, filePath) };
}

async function writeFrontendSpec(
  projectPath: string,
  frontendDir: string,
  entities: AnalysisEntity[],
  scan: RepositoryScanResult,
): Promise<GeneratedSpecArtifact | null> {
  const uiEntities = entities.filter(entity => hasUiSignals(
    entity.name,
    entity.sourcePath,
    entity.analysis,
  ));
  const uiPaths = collectRankedPaths(
    uiEntities.flatMap(entity => entity.analysis?.dependencies ?? []),
    projectPath,
  );

  const repositoryHasUiSignals = uiEntities.length > 0 || scan.notableFiles.some(file => hasUiSignals(file));
  if (!repositoryHasUiSignals) {
    return null;
  }

  const fileName = determineFrontendFileName(uiEntities, scan);
  const filePath = path.join(frontendDir, fileName);
  const localizationPaths = uiPaths.filter(file => /\bi18n\b|locale|\.toml$/i.test(file));
  const constraints = uniqueLimit(
    uiEntities.flatMap(entity => entity.analysis?.constraints ?? []),
    8,
  );

  const content = `# ${determineFrontendTitle(fileName)}

> Generated by Transpec deterministic postprocess from repository scan and enhanced analysis.

## Interaction Surfaces

${renderCapabilitySections(uiEntities, 'UI surface')}

## Key UI / TUI Paths

${renderBulletList(uiPaths.length > 0 ? uiPaths.map(file => `\`${file}\``) : ['No UI-specific paths were extracted from enhanced analysis.'])}

## Localization and Help Content

${renderBulletList(localizationPaths.length > 0 ? localizationPaths.map(file => `\`${file}\``) : ['No dedicated localization assets were detected.'])}

## Constraints

${renderBulletList(constraints.length > 0 ? constraints : ['No UI-specific constraints were extracted yet.'])}

## Validation Focus

- Verify menu / prompt navigation after structural changes.
- Verify locale resources and help text stay aligned with runtime behavior.
- Refresh this guide when terminal UI state or surface ownership changes.
`;

  await fs.writeFile(filePath, `${content.trim()}\n`);
  return { layer: 'frontend', path: toProjectRelativePath(projectPath, filePath) };
}

async function writeGuides(
  projectPath: string,
  guidesDir: string,
  preprocessContext: PreprocessContextFile,
  postprocessContext: PostprocessContextFile,
  entities: AnalysisEntity[],
  scan: RepositoryScanResult,
  generatedFiles: GeneratedSpecArtifact[],
): Promise<GeneratedSpecArtifact[]> {
  const guideArtifacts: GeneratedSpecArtifact[] = [];
  guideArtifacts.push(await writeCrossLayerGuide(projectPath, guidesDir, entities, scan));
  guideArtifacts.push(await writeCodeReuseGuide(projectPath, guidesDir, entities, scan));
  guideArtifacts.push(
    await writeRepositoryStateGuide(
      projectPath,
      guidesDir,
      preprocessContext,
      postprocessContext,
      entities,
      generatedFiles,
    ),
  );
  return guideArtifacts;
}

async function writeCrossLayerGuide(
  projectPath: string,
  guidesDir: string,
  entities: AnalysisEntity[],
  scan: RepositoryScanResult,
): Promise<GeneratedSpecArtifact> {
  const filePath = path.join(guidesDir, 'cross-layer-thinking-guide.md');
  const specs = entities.filter(entity => entity.type === 'spec');
  const uiEntities = entities.filter(entity => hasUiSignals(
    entity.name,
    entity.sourcePath,
    entity.analysis,
  ));
  const configPaths = uniqueLimit(
    scan.notableFiles.filter(file => /config|i18n|locale/i.test(file)),
    6,
  );
  const runtimePaths = uniqueLimit(
    [
      ...collectRankedPaths(
        specs.flatMap(entity => entity.analysis?.dependencies ?? []),
        projectPath,
      ),
      ...scan.notableFiles.filter(file => /main\.(rs|ts|js|py)$|remote|annotate|setup_ui/i.test(file)),
    ],
    8,
  );
  const uiPaths = uniqueLimit(
    [
      ...collectRankedPaths(
        uiEntities.flatMap(entity => entity.analysis?.dependencies ?? []),
        projectPath,
      ),
      ...scan.notableFiles.filter(file => /setup_ui|i18n|locale/i.test(file)),
    ],
    6,
  );

  const content = `# Cross-Layer Thinking Guide

> Generated by Transpec deterministic postprocess for repository-specific boundary checks.

## Repository-Specific Boundaries

### Configuration and runtime setup

${renderBulletList(
    configPaths.length > 0
      ? configPaths.map(file => `\`${file}\``)
      : ['No dedicated config or locale paths were detected in the repository scan.'],
  )}

### Runtime and command boundaries

${renderBulletList(
    runtimePaths.length > 0
      ? runtimePaths.map(file => `\`${file}\``)
      : ['No grounded runtime module paths were extracted from enhanced analysis.'],
  )}

### Interaction surfaces

${renderBulletList(
    uiPaths.length > 0
      ? uiPaths.map(file => `\`${file}\``)
      : ['No browser or terminal interaction layer was detected in the current repository state.'],
  )}

### Generated workflow artifacts

- \`.transpec/workspace/preprocess-context.json\`
- \`.transpec/workspace/enhanced-analysis.json\`
- \`.transpec/workspace/postprocess-context.json\`
- \`.trellis/spec/\`
- \`.trellis/tasks/archive/\`

## Before Implementing Cross-Layer Changes

- Map the flow from config or CLI input through runtime modules, output side effects, and any Trellis artifacts that must stay aligned.
- Decide where validation should happen once instead of scattering the same checks across command handlers, UI code, and emitted docs.
- Re-run \`transpec validate\` after any change that touches emitted task metadata, grounded spec paths, or runtime workspace JSON.

## Repo-Specific Checklist

- If config schema or defaults move, update the runtime loader paths and any setup or interaction surfaces that edit the same values.
- If command dispatch, remote logic, annotate flow, or setup behavior changes, re-check the grounded backend/frontend guides for ownership drift.
- If new interaction surfaces appear, update \`.trellis/spec/frontend/index.md\` and the related task context JSONL entries together.
- If emitted Trellis guide filenames move, update both the guide indexes and any archived task context that references those guides.
`;

  await writeManagedMarkdown(filePath, content, [GENERATED_GUIDE_MARKER]);
  return { layer: 'guides', path: toProjectRelativePath(projectPath, filePath) };
}

async function writeCodeReuseGuide(
  projectPath: string,
  guidesDir: string,
  entities: AnalysisEntity[],
  scan: RepositoryScanResult,
): Promise<GeneratedSpecArtifact> {
  const filePath = path.join(guidesDir, 'code-reuse-thinking-guide.md');
  const reusePaths = uniqueLimit(
    [
      ...collectRankedPaths(
        entities.flatMap(entity => entity.analysis?.dependencies ?? []),
        projectPath,
      ),
      ...scan.notableFiles.filter(file => /config|remote|annotate|setup_ui|i18n|locale/i.test(file)),
    ],
    10,
  );

  const content = `# Code Reuse Thinking Guide

> Generated by Transpec deterministic postprocess for repository-specific reuse hotspots.

## Reuse Hotspots

${renderBulletList(
    reusePaths.length > 0
      ? reusePaths.map(file => `Search \`${file}\` before adding new adjacent logic.`)
      : ['No concrete reuse hotspots were extracted yet; search the runtime root before creating new helpers.'],
  )}

## Search-First Checklist

- Reuse existing config, locale, remote, and command helpers before copying the same behavior into another module.
- When adding new task-context or guide references, update the shared generator or helper instead of patching one output file path at a time.
- If a path or contract appears in both deterministic postprocess output and validation rules, keep the rule in one helper and reuse it from both sides.

## Review Triggers

- Search for the same filename, guide path, or task metadata field before adding a new conversion rule.
- If the same repository path appears in multiple grounded docs, confirm it still represents a single source of truth.
- When adding a new emitted guide, make sure the corresponding index and task context entries are updated in the same change.
`;

  await writeManagedMarkdown(filePath, content, [GENERATED_GUIDE_MARKER]);
  return { layer: 'guides', path: toProjectRelativePath(projectPath, filePath) };
}

async function writeRepositoryStateGuide(
  projectPath: string,
  guidesDir: string,
  preprocessContext: PreprocessContextFile,
  postprocessContext: PostprocessContextFile,
  entities: AnalysisEntity[],
  generatedFiles: GeneratedSpecArtifact[],
): Promise<GeneratedSpecArtifact> {
  const filePath = path.join(guidesDir, 'repository-and-conversion-state.md');
  const hasTrellisScripts = await pathExists(path.join(projectPath, '.trellis', 'scripts'));
  const legacySpecCount = await countMarkdownFiles(path.join(projectPath, '.trellis', 'legacy', 'specs'));
  const { activeTaskCount, archivedTaskCount } = await countTaskDirectories(path.join(projectPath, '.trellis', 'tasks'));
  const taskContextCoverage = await countTaskContextCoverage(path.join(projectPath, '.trellis', 'tasks'));
  const analyzedCount = entities.filter(entity => entity.analysis).length;
  const groundedArtifacts = generatedFiles
    .filter(file => file.layer !== 'guides')
    .map(file => `\`${file.path}\``);

  const content = `# Repository and Conversion State

> Generated by Transpec deterministic postprocess from runtime workspace artifacts.

## Snapshot

- Source framework: ${preprocessContext.sourceFramework}
- Target framework: ${preprocessContext.targetFramework}
- Preprocess entities: ${preprocessContext.entityCount}
- Exported relations: ${preprocessContext.relationCount}
- Enhanced analysis coverage: ${analyzedCount}/${preprocessContext.entityCount}
- Deterministic apply output count: ${postprocessContext.entitiesTransformed}

## Trellis Layout State

- Legacy specs copied to \`.trellis/legacy/specs/\`: ${legacySpecCount}
- Active task directories under \`.trellis/tasks/\`: ${activeTaskCount}
- Archived task directories under \`.trellis/tasks/archive/\`: ${archivedTaskCount}
- Task context files present: ${taskContextCoverage.withAllContextFiles}/${taskContextCoverage.totalTasks}

## Grounded Spec Outputs

${renderBulletList(groundedArtifacts.length > 0 ? groundedArtifacts : ['No grounded spec artifacts were generated.'])}

## Runtime Contract Notes

- Workflow bootstrap file should live at \`.trellis/workflow.md\`.
- Backend / frontend / guide indexes should exist before Trellis skills run.
- Historical OpenSpec archive imports should remain in \`.trellis/tasks/archive/\`, not the active task pool.
- \`.transpec/workspace/preprocess-context.json\` should be refreshed after enhanced analysis changes.
- ${hasTrellisScripts
    ? 'The full `.trellis/scripts/` bundle is present in the current repository state.'
    : 'Transpec currently guarantees only the minimum Trellis runtime skeleton. If `.trellis/scripts/` is still missing after conversion, run `trellis update` and then `trellis init` to install the full Trellis workflow/tooling layer.'}

## Recommended Refresh Sequence

1. Run \`transpec preprocess\` to refresh RAW IR and preprocess context.
2. Regenerate \`.transpec/workspace/enhanced-analysis.json\`.
3. Run \`transpec preprocess --skip-convert\` to sync \`hasEnhancedAnalysis\`.
4. Run \`transpec apply\` to emit deterministic target artifacts.
5. Run \`transpec validate\` to confirm the converted project still satisfies Trellis runtime contracts.
`;

  await fs.writeFile(filePath, `${content.trim()}\n`);
  return { layer: 'guides', path: toProjectRelativePath(projectPath, filePath) };
}

async function writeWorkflowBootstrap(
  projectPath: string,
  scan: RepositoryScanResult,
  generatedFiles: GeneratedSpecArtifact[],
): Promise<void> {
  const workflowPath = path.join(projectPath, '.trellis', 'workflow.md');
  const hasFrontendDocs = generatedFiles.some(file => file.layer === 'frontend');
  const hasTrellisScripts = await pathExists(path.join(projectPath, '.trellis', 'scripts'));
  const language = detectPrimaryLanguage(scan);

  const content = `# Development Workflow

> ${WORKFLOW_GROUNDED_MARKER}

This converted repository keeps historical source specs under \`.trellis/legacy/specs/\` and imported historical work under \`.trellis/tasks/archive/\`. Start new work from the grounded Trellis docs below instead of treating the imported OpenSpec artifacts as the active workflow layer.

## Quick Start

1. Read \`.trellis/spec/backend/index.md\` and \`.trellis/spec/guides/index.md\` before runtime or conversion-contract changes.
2. ${hasFrontendDocs
    ? 'Read `.trellis/spec/frontend/index.md` before terminal UI or other interaction-surface changes.'
    : 'Use `.trellis/spec/frontend/index.md` only if the repository later grows a browser or interaction-layer surface.'}
3. Treat \`.trellis/tasks/archive/\` as imported history; create new work under \`.trellis/tasks/\`.
4. Run \`transpec apply\` and \`transpec validate\` after changing conversion inputs or deterministic Trellis output rules.

## Grounded Docs

- Backend/runtime guides live under \`.trellis/spec/backend/\`.
- Frontend or interaction-surface guides live under \`.trellis/spec/frontend/\`.
- Cross-layer and repository-state guides live under \`.trellis/spec/guides/\`.

## Repository Notes

- Primary language detected from repository scan: ${language.label}
- Runtime workspace artifacts live under \`.transpec/workspace/\`.
- The imported archive is historical context, not an active task queue.
- ${hasTrellisScripts
    ? 'The full `.trellis/scripts/` bundle is present in the current repository state.'
    : 'Only the minimum Trellis runtime skeleton is currently present. Install the full Trellis workflow/tooling bundle with `trellis update` and `trellis init` if you need local Trellis scripts and task automation.'}
`;

  await writeManagedMarkdown(workflowPath, content, [WORKFLOW_BASELINE_MARKER, WORKFLOW_GROUNDED_MARKER]);
}

async function writeBackendIndex(
  indexPath: string,
  artifacts: GeneratedSpecArtifact[],
  scan: RepositoryScanResult,
): Promise<void> {
  const language = detectPrimaryLanguage(scan);
  const repoLooksCli = scan.notableFiles.some(file => /cargo\.toml$|package\.json$|main\.(rs|ts|js|py)$/i.test(file));
  const content = `# Backend Development Guidelines

> ${BACKEND_INDEX_GROUNDED_MARKER}

## Snapshot

- Primary language: ${language.label}
- Runtime shape: ${repoLooksCli ? 'CLI / terminal workflow' : 'repository runtime'}
- Grounded backend guides: ${artifacts.length}

## Pre-Development Checklist

- Start with the grounded guide below that matches the module or contract you are changing.
- Read [Cross Layer Thinking Guide](../guides/cross-layer-thinking-guide.md) when a change spans runtime modules, emitted artifacts, or interaction surfaces.
- Re-run \`transpec postprocess\` after large repository-structure changes so guide paths stay accurate.

## Available Guides

${renderIndexEntries(
    artifacts,
    'No grounded backend guides were generated yet for the current repository state.',
    'Grounded runtime/capability guide derived from conversion output',
  )}
`;

  await writeManagedMarkdown(indexPath, content, [BACKEND_INDEX_BASELINE_MARKER, BACKEND_INDEX_GROUNDED_MARKER]);
}

async function writeFrontendIndex(
  indexPath: string,
  artifacts: GeneratedSpecArtifact[],
  scan: RepositoryScanResult,
): Promise<void> {
  const repositoryHasUiSignals = artifacts.length > 0 || scan.notableFiles.some(file => hasUiSignals(file));
  const content = `# Frontend Development Guidelines

> ${FRONTEND_INDEX_GROUNDED_MARKER}

## Snapshot

- Interaction surfaces detected: ${artifacts.length}
- Repository frontend shape: ${repositoryHasUiSignals ? 'terminal UI / interaction surfaces present' : 'no dedicated frontend or terminal UI detected'}

## Pre-Development Checklist

- Read the grounded guide below before changing menu flow, prompts, help text, locale resources, or other interaction surfaces.
- Read [Cross Layer Thinking Guide](../guides/cross-layer-thinking-guide.md) when UI changes also affect config, command dispatch, or emitted artifacts.
- Keep \`.trellis/spec/frontend/index.md\` aligned with actual UI surface ownership as the repository evolves.

## Available Guides

${renderIndexEntries(
    artifacts,
    'No grounded frontend guides were generated because no interaction surface was detected.',
    'Grounded interaction-surface guide derived from conversion output',
  )}
`;

  await writeManagedMarkdown(indexPath, content, [FRONTEND_INDEX_BASELINE_MARKER, FRONTEND_INDEX_GROUNDED_MARKER]);
}

async function writeGuidesIndex(
  indexPath: string,
  artifacts: GeneratedSpecArtifact[],
): Promise<void> {
  const content = `# Thinking Guides

> ${GUIDES_INDEX_GROUNDED_MARKER}

## When To Reach For These Guides

- Use the cross-layer guide when a change crosses config, runtime code, interaction surfaces, emitted task metadata, or Trellis artifacts.
- Use the code-reuse guide before adding new helpers, new emitted guide paths, or new task-context references.
- Use repository-and-conversion-state when you need the current conversion snapshot, archive layout, or refresh sequence.

## Available Guides

${renderIndexEntries(
    artifacts,
    'No grounded guide documents were generated yet for the current repository state.',
    'Grounded repository or workflow-thinking guide derived from conversion output',
  )}
`;

  await writeManagedMarkdown(indexPath, content, [GUIDES_INDEX_BASELINE_MARKER, GUIDES_INDEX_GROUNDED_MARKER]);
}

async function readJsonFile<T>(filePath: string): Promise<T> {
  const content = await fs.readFile(filePath, 'utf-8');
  return JSON.parse(content) as T;
}

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function scanRepository(projectPath: string): Promise<RepositoryScanResult> {
  const extensionCounts = new Map<string, number>();
  const filesByExtension = new Map<string, string[]>();
  const topLevelDirectoryCounts = new Map<string, number>();
  const notableFiles: string[] = [];

  async function walk(currentPath: string, depth: number): Promise<void> {
    if (depth > 5) {
      return;
    }

    let entries: string[];
    try {
      entries = await fs.readdir(currentPath);
    } catch {
      return;
    }

    for (const entry of entries) {
      if (SKIPPED_SCAN_DIRECTORIES.has(entry)) {
        continue;
      }

      const fullPath = path.join(currentPath, entry);
      let stat;
      try {
        stat = await fs.stat(fullPath);
      } catch {
        continue;
      }

      if (stat.isDirectory()) {
        await walk(fullPath, depth + 1);
        continue;
      }

      const relativePath = toProjectRelativePath(projectPath, fullPath);
      const extension = path.extname(entry).toLowerCase() || '[no-extension]';
      extensionCounts.set(extension, (extensionCounts.get(extension) ?? 0) + 1);

      const existing = filesByExtension.get(extension) ?? [];
      if (existing.length < 25) {
        existing.push(relativePath);
        filesByExtension.set(extension, existing);
      }

      const root = relativePath.split('/')[0] ?? '.';
      topLevelDirectoryCounts.set(root, (topLevelDirectoryCounts.get(root) ?? 0) + 1);

      if (
        /cargo\.toml$|package\.json$|main\.(rs|ts|js|py)$|setup_ui\.(rs|ts|js|tsx)$|i18n|locale/i.test(relativePath)
      ) {
        notableFiles.push(relativePath);
      }
    }
  }

  await walk(projectPath, 0);
  return { extensionCounts, filesByExtension, topLevelDirectoryCounts, notableFiles };
}

function detectPrimaryLanguage(scan: RepositoryScanResult): LanguageProfile {
  const candidates: Array<{ extension: string; label: string; key: string }> = [
    { extension: '.rs', label: 'Rust', key: 'rust' },
    { extension: '.ts', label: 'TypeScript', key: 'typescript' },
    { extension: '.tsx', label: 'TypeScript', key: 'typescript' },
    { extension: '.js', label: 'JavaScript', key: 'javascript' },
    { extension: '.jsx', label: 'JavaScript', key: 'javascript' },
    { extension: '.py', label: 'Python', key: 'python' },
    { extension: '.go', label: 'Go', key: 'go' },
  ];

  let best: LanguageProfile = { key: 'generic', label: 'Repository' };
  let bestCount = 0;

  for (const candidate of candidates) {
    const count = scan.extensionCounts.get(candidate.extension) ?? 0;
    if (count > bestCount) {
      best = { key: candidate.key, label: candidate.label };
      bestCount = count;
    }
  }

  return best;
}

function determineBackendFileName(language: LanguageProfile, repoLooksCli: boolean): string {
  if (language.key === 'rust' && repoLooksCli) {
    return 'rust-cli-runtime.md';
  }
  if (language.key === 'typescript' && repoLooksCli) {
    return 'typescript-cli-runtime.md';
  }
  if (language.key === 'python' && repoLooksCli) {
    return 'python-cli-runtime.md';
  }
  if (language.key === 'rust') {
    return 'rust-runtime.md';
  }
  return 'repository-runtime.md';
}

function determineBackendTitle(language: LanguageProfile, repoLooksCli: boolean): string {
  if (language.key === 'generic') {
    return 'Repository Runtime';
  }
  return repoLooksCli ? `${language.label} CLI Runtime` : `${language.label} Runtime`;
}

function determineFrontendFileName(entities: AnalysisEntity[], scan: RepositoryScanResult): string {
  const hasTerminalSignal = entities.some(entity => /\bterminal|menu|setup|interactive|tui\b/i.test(entity.name))
    || scan.notableFiles.some(file => /setup_ui|terminal|menu/i.test(file));
  return hasTerminalSignal ? 'terminal-setup-ui.md' : 'interaction-surfaces.md';
}

function determineFrontendTitle(fileName: string): string {
  return fileName === 'terminal-setup-ui.md' ? 'Terminal Setup UI' : 'Interaction Surfaces';
}

function renderCapabilitySections(entities: AnalysisEntity[], fallbackLabel: string): string {
  if (entities.length === 0) {
    return '- No grounded entities were available for this layer.';
  }

  return entities
    .map(entity => {
      const intent = entity.analysis?.intent ?? `No ${fallbackLabel.toLowerCase()} intent extracted yet.`;
      const dependencies = uniqueLimit(entity.analysis?.dependencies ?? [], 4);
      const constraints = uniqueLimit(entity.analysis?.constraints ?? [], 3);
      return `### ${entity.name}

- Intent: ${intent}
- Source: \`${entity.sourcePath}\`
- Dependencies: ${dependencies.length > 0 ? dependencies.map(dep => `\`${dep}\``).join(', ') : 'None extracted'}
- Constraints: ${constraints.length > 0 ? constraints.join('; ') : 'None extracted'}`;
    })
    .join('\n\n');
}

function renderBulletList(items: string[]): string {
  return items.map(item => `- ${item}`).join('\n');
}

function formatInlineList(items: string[]): string {
  return items.length > 0 ? items.join(', ') : 'None detected';
}

function collectRankedPaths(paths: string[], projectPath: string): string[] {
  const counts = new Map<string, number>();

  for (const rawPath of paths) {
    if (!rawPath || rawPath.startsWith('openspec/') || rawPath.startsWith('.trellis/') || rawPath.startsWith('.transpec/')) {
      continue;
    }

    const normalized = normalizeDependencyPath(rawPath, projectPath);
    counts.set(normalized, (counts.get(normalized) ?? 0) + 1);
  }

  return [...counts.entries()]
    .sort((a, b) => (b[1] - a[1]) || a[0].localeCompare(b[0]))
    .slice(0, 12)
    .map(([file]) => file);
}

function normalizeDependencyPath(rawPath: string, projectPath: string): string {
  if (path.isAbsolute(rawPath)) {
    return toProjectRelativePath(projectPath, rawPath);
  }
  return rawPath.replace(/\\/g, '/');
}

function collectTopRoots(scan: RepositoryScanResult): string[] {
  return [...scan.topLevelDirectoryCounts.entries()]
    .sort((a, b) => (b[1] - a[1]) || a[0].localeCompare(b[0]))
    .slice(0, 5)
    .map(([root]) => `\`${root}/\``);
}

function uniqueLimit(values: string[], limit: number): string[] {
  return [...new Set(values.filter(Boolean).map(value => value.trim()))].slice(0, limit);
}

function toIndexLabel(relativePath: string): string {
  const baseName = path.basename(relativePath, '.md');
  return baseName
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function renderIndexEntries(
  artifacts: GeneratedSpecArtifact[],
  fallback: string,
  description: string,
): string {
  if (artifacts.length === 0) {
    return `- ${fallback}`;
  }

  return artifacts
    .map(file => `- [${toIndexLabel(file.path)}](./${path.basename(file.path)}) - ${description}`)
    .join('\n');
}

async function writeManagedMarkdown(
  filePath: string,
  content: string,
  managedMarkers: string[],
): Promise<void> {
  let shouldWrite = true;

  try {
    const existing = await fs.readFile(filePath, 'utf-8');
    shouldWrite = managedMarkers.some(marker => existing.includes(marker));
  } catch {
    shouldWrite = true;
  }

  if (!shouldWrite) {
    return;
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, `${content.trim()}\n`);
}

async function countMarkdownFiles(root: string): Promise<number> {
  let count = 0;

  async function walk(currentPath: string): Promise<void> {
    let entries: string[];
    try {
      entries = await fs.readdir(currentPath);
    } catch {
      return;
    }

    for (const entry of entries) {
      const fullPath = path.join(currentPath, entry);
      let stat;
      try {
        stat = await fs.stat(fullPath);
      } catch {
        continue;
      }

      if (stat.isDirectory()) {
        await walk(fullPath);
        continue;
      }

      if (entry.endsWith('.md')) {
        count += 1;
      }
    }
  }

  await walk(root);
  return count;
}

async function countTaskDirectories(tasksRoot: string): Promise<{ activeTaskCount: number; archivedTaskCount: number }> {
  const activeTaskCount = await countImmediateDirectories(tasksRoot, new Set(['archive']));
  const archivedTaskCount = await countArchiveDirectories(path.join(tasksRoot, 'archive'));
  return { activeTaskCount, archivedTaskCount };
}

async function countImmediateDirectories(root: string, ignored: Set<string> = new Set()): Promise<number> {
  try {
    const entries = await fs.readdir(root);
    let count = 0;
    for (const entry of entries) {
      if (ignored.has(entry)) {
        continue;
      }
      const fullPath = path.join(root, entry);
      const stat = await fs.stat(fullPath);
      if (stat.isDirectory()) {
        count += 1;
      }
    }
    return count;
  } catch {
    return 0;
  }
}

async function countArchiveDirectories(archiveRoot: string): Promise<number> {
  try {
    const months = await fs.readdir(archiveRoot);
    let count = 0;
    for (const month of months) {
      const monthPath = path.join(archiveRoot, month);
      const stat = await fs.stat(monthPath);
      if (!stat.isDirectory()) {
        continue;
      }
      count += await countImmediateDirectories(monthPath);
    }
    return count;
  } catch {
    return 0;
  }
}

async function countTaskContextCoverage(tasksRoot: string): Promise<{ totalTasks: number; withAllContextFiles: number }> {
  const taskDirs = await collectTaskDirectories(tasksRoot);
  let withAllContextFiles = 0;

  for (const taskDir of taskDirs) {
    const hasAllFiles = await Promise.all([
      fs.access(path.join(taskDir, 'implement.jsonl')).then(() => true).catch(() => false),
      fs.access(path.join(taskDir, 'check.jsonl')).then(() => true).catch(() => false),
      fs.access(path.join(taskDir, 'debug.jsonl')).then(() => true).catch(() => false),
    ]);
    if (hasAllFiles.every(Boolean)) {
      withAllContextFiles += 1;
    }
  }

  return { totalTasks: taskDirs.length, withAllContextFiles };
}

async function collectTaskDirectories(tasksRoot: string): Promise<string[]> {
  const directories: string[] = [];
  const activeRoot = tasksRoot;
  const archiveRoot = path.join(tasksRoot, 'archive');

  try {
    const entries = await fs.readdir(activeRoot);
    for (const entry of entries) {
      if (entry === 'archive') {
        continue;
      }
      const fullPath = path.join(activeRoot, entry);
      const stat = await fs.stat(fullPath);
      if (stat.isDirectory()) {
        directories.push(fullPath);
      }
    }
  } catch {
    // Ignore missing task root.
  }

  try {
    const months = await fs.readdir(archiveRoot);
    for (const month of months) {
      const monthPath = path.join(archiveRoot, month);
      const stat = await fs.stat(monthPath);
      if (!stat.isDirectory()) {
        continue;
      }
      const taskEntries = await fs.readdir(monthPath);
      for (const taskEntry of taskEntries) {
        const taskPath = path.join(monthPath, taskEntry);
        const taskStat = await fs.stat(taskPath);
        if (taskStat.isDirectory()) {
          directories.push(taskPath);
        }
      }
    }
  } catch {
    // Ignore missing archive root.
  }

  return directories;
}
