/**
 * Trellis Framework Adapter
 *
 * Parses Trellis format to Core IR and emits Core IR to Trellis format.
 *
 * Trellis Structure:
 * - .trellis/
 *   ├── config.yaml
 *   ├── spec/
 *   │   ├── backend/
 *   │   │   ├── index.md
 *   │   │   └── *.md
 *   │   ├── frontend/
 *   │   │   └── *.md
 *   │   └── guides/
 *   │       └── *.md
 *   ├── tasks/
 *   │   └── {MM-DD-slug-assignee}/
 *   │       ├── task.json
 *   │       ├── prd.md
 *   │       ├── implement.jsonl
 *   │       └── check.jsonl
 *   └── workspace/
 *       └── {developer}/
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { BaseFrameworkAdapter, FrameworkDetails } from '../base-adapter.js';
import { CoreEntity, CoreType, FrameworkType } from '../../ir/types.js';
import { getLogger, LogModules } from '../../logging/index.js';
import { buildEntitySignalHaystack, hasUiSignals } from '../task-signals.js';

const logger = getLogger(LogModules.ADAPTER);
const DEFAULT_TASK_NEXT_ACTIONS = [
  { phase: 1, action: 'brainstorm' },
  { phase: 2, action: 'research' },
  { phase: 3, action: 'implement' },
  { phase: 4, action: 'check' },
  { phase: 5, action: 'update-spec' },
  { phase: 6, action: 'record-session' },
];
const DEFAULT_CHECK_CONTEXT = [
  { file: '.agents/skills/finish-work/SKILL.md', reason: 'Finish work checklist' },
  { file: '.agents/skills/check/SKILL.md', reason: 'Code quality check spec' },
];
const DEFAULT_DEBUG_CONTEXT = [
  { file: '.agents/skills/check/SKILL.md', reason: 'Code quality check spec' },
];
const TRELLIS_WORKFLOW_TEMPLATE = `# Development Workflow

> Generated by Transpec as a minimum Trellis runtime skeleton.

This file provides the workflow contract required by Trellis session tooling until project-specific workflow guidance is refined.

## Quick Start

1. Run \`python3 ./.trellis/scripts/get_context.py\` for session context.
2. Read \`.trellis/spec/backend/index.md\`, \`.trellis/spec/frontend/index.md\`, and \`.trellis/spec/guides/index.md\`.
3. Use \`.trellis/tasks/\` for active work and \`.trellis/tasks/archive/\` for historical imported tasks.

## Task Lifecycle

- Create tasks with \`python3 ./.trellis/scripts/task.py create "<title>"\`
- Initialize task context with \`python3 ./.trellis/scripts/task.py init-context <dir> <dev_type>\`
- Archive completed tasks with \`python3 ./.trellis/scripts/task.py archive <task-name>\`

## Notes

- OpenSpec feature specifications are preserved under \`.trellis/legacy/specs/\`.
- Trellis development specs under \`.trellis/spec/\` should be updated to reflect the actual codebase after conversion.
`;
const TRELLIS_BACKEND_INDEX_TEMPLATE = `# Backend Development Guidelines

> Generated baseline Trellis backend index.

## Pre-Development Checklist

- Read this index before backend or CLI changes.
- Read the specific backend guideline files that match your task.
- Update these documents when converter behavior or runtime contracts change.

## Available Guides

- Add project-specific backend guides here as the codebase is analyzed.
`;
const TRELLIS_FRONTEND_INDEX_TEMPLATE = `# Frontend Development Guidelines

> Generated baseline Trellis frontend index.

## Pre-Development Checklist

- Read this index before frontend changes.
- Add or refine frontend guides once the converted project structure is understood.

## Available Guides

- Add project-specific frontend guides here as the codebase is analyzed.
`;
const TRELLIS_GUIDES_INDEX_TEMPLATE = `# Thinking Guides

> Generated baseline Trellis guide index.

## Available Guides

- Use \`cross-layer-thinking-guide.md\` for workflow/runtime contract changes that span parse, transform, emit, and generated artifacts.
- Use \`code-reuse-thinking-guide.md\` when similar conversion logic exists in multiple places.
`;
const SKIPPED_SCAN_DIRECTORIES = new Set([
  '.git',
  '.trellis',
  '.transpec',
  'build',
  'coverage',
  'dist',
  'node_modules',
  'target',
  'tmp',
]);

export class TrellisAdapter extends BaseFrameworkAdapter {
  readonly framework: FrameworkType = 'trellis';
  readonly coreTypes: CoreType[] = [CoreType.DOCUMENT, CoreType.WORKFLOW];
  readonly supportedExtendedTypes = ['spec', 'task'];
  private readonly ensuredSkeletonRoots = new Set<string>();
  private readonly detectedDevTypes = new Map<string, 'backend' | 'frontend' | 'fullstack'>();
  private readonly detectedBaseBranches = new Map<string, string | null>();

  private readonly markers = [
    '.trellis/config.yaml',
    '.trellis/tasks/',
    '.trellis/spec/'
  ];

  async detect(projectPath: string): Promise<boolean> {
    for (const marker of this.markers) {
      const fullPath = path.join(projectPath, marker);
      try {
        await fs.access(fullPath);
        logger.debug('Trellis marker found', { path: fullPath });
        return true;
      } catch {
        continue;
      }
    }
    return false;
  }

  async getDetails(projectPath: string): Promise<FrameworkDetails> {
    const trellisPath = path.join(projectPath, '.trellis');
    let specCount = 0;
    let taskCount = 0;

    try {
      const specsPath = path.join(trellisPath, 'spec');
      specCount = await this.countFiles(specsPath, '.md');
      logger.debug('Spec files count', { count: specCount });

      const tasksPath = path.join(trellisPath, 'tasks');
      taskCount = await this.countDirectories(tasksPath);
      logger.debug('Task directories count', { count: taskCount });
    } catch (error) {
      logger.warn('Error getting Trellis details', { error });
    }

    return {
      framework: 'trellis',
      version: await this.getVersion(trellisPath),
      path: trellisPath,
      entityCount: specCount + taskCount,
      additionalInfo: { specCount, taskCount }
    };
  }

  async parseFile(filePath: string): Promise<CoreEntity> {
    const content = await fs.readFile(filePath, 'utf-8');
    const relativePath = path.relative(process.cwd(), filePath);

    logger.debug('Parsing Trellis file', { path: filePath, relativePath });

    const isTask = relativePath.includes('/tasks/') || relativePath.includes('\\tasks\\');
    const extendedType = isTask ? 'task' : 'spec';
    const name = this.extractName(filePath);
    const now = new Date().toISOString();

    const metadata = this.parseMetadata(content, extendedType, filePath);

    const createdAt = (metadata.createdAt as string) || now;
    const updatedAt = (metadata.updatedAt as string) || createdAt;

    return {
      id: this.buildEntityId(filePath, extendedType),
      name,
      coreType: isTask ? CoreType.WORKFLOW : CoreType.DOCUMENT,
      extendedType,
      content,
      metadata,
      sourceFramework: 'trellis',
      sourcePath: filePath,
      createdAt,
      updatedAt,
    };
  }

  async parseAll(projectPath: string): Promise<CoreEntity[]> {
    const entities: CoreEntity[] = [];
    const trellisPath = path.join(projectPath, '.trellis');

    logger.info('Parsing all Trellis entities', { path: trellisPath });

    // Parse specs
    const specsPath = path.join(trellisPath, 'spec');
    try {
      const specEntities = await this.parseSpecDirectory(specsPath);
      entities.push(...specEntities);
    } catch (error) {
      logger.warn('Spec directory not found', { path: specsPath });
    }

    // Parse tasks
    const tasksPath = path.join(trellisPath, 'tasks');
    try {
      const taskDirs = await fs.readdir(tasksPath);
      logger.debug('Found task directories', { count: taskDirs.length });

      for (const dir of taskDirs) {
        const taskDir = path.join(tasksPath, dir);
        const stat = await fs.stat(taskDir);
        if (!stat.isDirectory()) continue;

        // Parse prd.md if exists
        const prdFile = path.join(taskDir, 'prd.md');
        try {
          const entity = await this.parseFile(prdFile);
          entities.push(entity);
          logger.debug('Parsed task', { name: entity.name, id: entity.id });
        } catch (error) {
          logger.warn('Failed to parse task prd', { file: prdFile });
        }

        // Also parse task.json for metadata
        const taskJsonFile = path.join(taskDir, 'task.json');
        try {
          const taskJson = await fs.readFile(taskJsonFile, 'utf-8');
          const taskData = JSON.parse(taskJson);
          // Attach task.json data to the last entity's metadata
          const lastEntity = entities[entities.length - 1];
          if (lastEntity && lastEntity.extendedType === 'task') {
            lastEntity.metadata.taskJson = taskData;
            if (typeof taskData.id === 'string' && taskData.id.trim()) {
              lastEntity.id = this.generateStableId('trellis-task', `task:${taskData.id.trim().toLowerCase()}`);
            }
          }
        } catch {
          // task.json might not exist
        }
      }
    } catch (error) {
      logger.warn('Tasks directory not found', { path: tasksPath });
    }

    logger.info('Trellis parsing complete', { entities: entities.length });
    return entities;
  }

  async emit(entity: CoreEntity, targetPath: string): Promise<void> {
    logger.debug('Emitting Trellis entity', { name: entity.name, type: entity.extendedType });
    await this.ensureWorkflowSkeleton(targetPath);

    const isTask = entity.extendedType === 'task';

    if (isTask) {
      const sourceCreatedAt = this.resolveSourceCreatedAt(entity);
      const taskSlug = this.resolveTaskSlug(entity);
      const directoryName = this.buildTaskDirectoryName(taskSlug, sourceCreatedAt);
      const archiveMonth = this.resolveArchiveMonth(entity, sourceCreatedAt);
      const baseDir = Boolean(entity.metadata.isArchived)
        ? path.join(targetPath, '.trellis', 'tasks', 'archive', archiveMonth, directoryName)
        : path.join(targetPath, '.trellis', 'tasks', directoryName);
      await fs.mkdir(baseDir, { recursive: true });

      // Emit prd.md (proposal content)
      const prdPath = path.join(baseDir, 'prd.md');
      await fs.writeFile(prdPath, entity.content);
      logger.debug('Emitted prd.md', { path: prdPath });

      const subtasks = entity.metadata.subtasks as Array<{ name: string; status: string }> | undefined;
      const sourceStatus = typeof entity.metadata.sourceStatus === 'string'
        ? entity.metadata.sourceStatus
        : undefined;
      const taskContext = await this.resolveTaskContext(targetPath, entity);
      const devType = taskContext.devType;
      const baseBranch = await this.detectBaseBranch(targetPath);
      const status = this.determineStatus(sourceStatus, subtasks, Boolean(entity.metadata.isArchived));
      const isCompleted = status === 'completed';
      const importedAt = new Date().toISOString();
      const preservedSourceFiles = this.buildPreservedSourceFiles(entity);
      const sourceTaskSummary = typeof entity.metadata.sourceTaskSummary === 'string'
        ? entity.metadata.sourceTaskSummary
        : null;
      const sourceAcceptanceCriteria = Array.isArray(entity.metadata.sourceAcceptanceCriteria)
        ? entity.metadata.sourceAcceptanceCriteria
        : [];
      const sourceFollowUpSuggestions = Array.isArray(entity.metadata.sourceFollowUpSuggestions)
        ? entity.metadata.sourceFollowUpSuggestions
        : [];
      const sourceTaskEstimates = Array.isArray(entity.metadata.sourceTaskEstimates)
        ? entity.metadata.sourceTaskEstimates
        : [];
      const sourceTaskSections = Array.isArray(entity.metadata.sourceTaskSections)
        ? entity.metadata.sourceTaskSections
        : [];

      const taskJson = {
        id: taskSlug,
        name: taskSlug,
        title: this.resolveTaskTitle(entity),
        description: this.resolveTaskDescription(entity),
        status,
        dev_type: devType,
        scope: null,
        package: null,
        priority: 'P2',
        creator: 'transpec',
        assignee: this.resolveAssignee(entity),
        createdAt: sourceCreatedAt,
        completedAt: isCompleted ? this.resolveCompletedAt(entity) : null,
        branch: null,
        base_branch: baseBranch,
        worktree_path: null,
        current_phase: isCompleted ? DEFAULT_TASK_NEXT_ACTIONS.length : 0,
        next_action: isCompleted ? [] : DEFAULT_TASK_NEXT_ACTIONS,
        commit: null,
        pr_url: null,
        subtasks: subtasks?.map((t, idx) => ({
          id: `${idx + 1}`,
          name: t.name,
          status: t.status,
        })) || [],
        children: [],
        parent: null,
        relatedFiles: entity.metadata.relatedFiles || [],
        notes: `Converted from OpenSpec change: ${entity.sourcePath}`,
        meta: {
          convertedFrom: entity.sourceFramework,
          originalExtendedType: this.resolveSourceExtendedType(entity),
          sourceFramework: entity.sourceFramework,
          sourcePath: entity.sourcePath,
          sourceCreatedAt,
          sourceUpdatedAt: this.resolveSourceUpdatedAt(entity),
          sourceArchivedAt: this.resolveSourceArchivedAt(entity),
          sourceStatus: sourceStatus || null,
          importedAt,
          isArchived: Boolean(entity.metadata.isArchived),
          preservedSourceFiles,
          sourceTaskSummary,
          sourceAcceptanceCriteria,
          sourceFollowUpSuggestions,
          sourceTaskEstimates,
          sourceTaskSections,
        },
      };

      await fs.writeFile(path.join(baseDir, 'task.json'), JSON.stringify(taskJson, null, 2));
      logger.debug('Emitted task.json', { path: baseDir, subtasks: subtasks?.length || 0 });
      await this.writeTaskContextFiles(baseDir, taskContext.implementEntries);

      // Optionally emit design.md if available
      if (entity.metadata.designContent) {
        await fs.writeFile(path.join(baseDir, 'design.md'), entity.metadata.designContent as string);
        logger.debug('Emitted design.md', { path: baseDir });
      }
      await this.writePreservedSourceArtifacts(baseDir, entity);
    } else {
      // OpenSpec specs describe features (what the project does)
      // Trellis spec/ describes development guidelines (how to develop)
      // These are semantically different - OpenSpec specs go to legacy/
      // Trellis spec/ must be generated separately via transpec init
      const legacyDir = path.join(targetPath, '.trellis', 'legacy', 'specs', this.slugify(entity.name));
      await fs.mkdir(legacyDir, { recursive: true });

      const specPath = path.join(legacyDir, 'spec.md');
      await fs.writeFile(specPath, entity.content);
      logger.debug('Emitted spec to legacy location (Trellis spec/ is generated separately)', { path: specPath });
    }
  }

  getFilePatterns(): string[] {
    return [
      '.trellis/spec/**/*.md',
      '.trellis/tasks/*/prd.md'
    ];
  }

  protected getTypeMapping(): Record<string, CoreType> {
    return {
      'spec': CoreType.DOCUMENT,
      'task': CoreType.WORKFLOW
    };
  }

  protected getReverseTypeMapping(): Record<CoreType, string[]> {
    return {
      [CoreType.DOCUMENT]: ['spec'],
      [CoreType.WORKFLOW]: ['task']
    };
  }

  private async parseSpecDirectory(specsPath: string): Promise<CoreEntity[]> {
    const entities: CoreEntity[] = [];

    async function walkDir(dir: string, subPath: string = '') {
      const entries = await fs.readdir(dir);
      for (const entry of entries) {
        const fullPath = path.join(dir, entry);
        const stat = await fs.stat(fullPath);

        if (stat.isDirectory()) {
          await walkDir(fullPath, `${subPath}/${entry}`);
        } else if (entry.endsWith('.md') && entry !== 'index.md') {
          const entity = await new TrellisAdapter().parseFile(fullPath);
          entity.name = `${subPath}/${entry}`.replace(/^\//, '').replace(/\.md$/, '');
          entities.push(entity);
        }
      }
    }

    await walkDir(specsPath);
    return entities;
  }

  private async countFiles(dir: string, extension: string): Promise<number> {
    let count = 0;

    async function walk(d: string) {
      try {
        const entries = await fs.readdir(d);
        for (const entry of entries) {
          const fullPath = path.join(d, entry);
          const stat = await fs.stat(fullPath);
          if (stat.isDirectory()) {
            await walk(fullPath);
          } else if (entry.endsWith(extension)) {
            count++;
          }
        }
      } catch {
        // Ignore
      }
    }

    await walk(dir);
    return count;
  }

  private async countDirectories(dir: string): Promise<number> {
    try {
      const entries = await fs.readdir(dir);
      let count = 0;
      for (const entry of entries) {
        const fullPath = path.join(dir, entry);
        const stat = await fs.stat(fullPath);
        if (stat.isDirectory()) count++;
      }
      return count;
    } catch {
      return 0;
    }
  }

  private parseMetadata(content: string, extendedType: string, filePath: string): Record<string, unknown> {
    const metadata: Record<string, unknown> = {
      originalPath: filePath,
    };

    // Extract frontmatter if present
    const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---\n/);
    if (frontmatterMatch) {
      try {
        const frontmatter = frontmatterMatch[1];
        const lines = frontmatter.split('\n');
        for (const line of lines) {
          const match = line.match(/^(\w+):\s*(.+)$/);
          if (match) {
            let value: string | number | boolean = match[2].replace(/["']/g, '');
            if (value === 'true') value = true;
            if (value === 'false') value = false;
            if (!isNaN(Number(value))) value = Number(value);
            metadata[match[1]] = value;
          }
        }
      } catch (error) {
        logger.warn('Failed to parse frontmatter', { file: filePath });
      }
    }

    // Extract frontmatter from YAML content blocks
    if (extendedType === 'task') {
      // Look for task status, priority, etc.
      const statusMatch = content.match(/Status:\s*(.+)/i);
      const priorityMatch = content.match(/Priority:\s*(.+)/i);
      const assigneeMatch = content.match(/Assignee:\s*(.+)/i);

      if (statusMatch) metadata.status = statusMatch[1].trim();
      if (priorityMatch) metadata.priority = priorityMatch[1].trim();
      if (assigneeMatch) metadata.assignee = assigneeMatch[1].trim();
    }

    return metadata;
  }

  private extractName(filePath: string): string {
    const parts = filePath.split(/[/\\]/);
    const fileName = parts[parts.length - 1];
    const dirName = parts[parts.length - 2];

    // For tasks, use directory name
    if (fileName === 'prd.md') {
      return dirName.replace(/^\d{2}-\d{2}-/, ''); // Remove date prefix
    }

    // For specs, use filename without extension
    return fileName.replace(/\.md$/, '');
  }

  private buildEntityId(filePath: string, extendedType: string): string {
    if (extendedType === 'task') {
      return this.generateStableId(
        'trellis-task',
        this.resolveTaskSeed(filePath),
      );
    }

    return this.generateStableId(
      'trellis-spec',
      this.resolveSpecSeed(filePath),
    );
  }

  private resolveTaskSeed(filePath: string): string {
    const normalizedPath = filePath.replace(/\\/g, '/');
    const match = normalizedPath.match(/\/\.trellis\/tasks\/(?:archive\/[^/]+\/)?([^/]+)\/prd\.md$/);
    if (match) {
      return `task:${match[1].toLowerCase()}`;
    }

    return `task:${path.basename(path.dirname(filePath)).toLowerCase()}`;
  }

  private resolveSpecSeed(filePath: string): string {
    const normalizedPath = filePath.replace(/\\/g, '/');
    const match = normalizedPath.match(/\/\.trellis\/spec\/(.+?)\.md$/);
    if (match) {
      return `spec:${match[1].toLowerCase()}`;
    }

    return `spec:${path.basename(filePath, '.md').toLowerCase()}`;
  }

  private async getVersion(trellisPath: string): Promise<string | undefined> {
    try {
      const versionFile = path.join(trellisPath, '.version');
      return await fs.readFile(versionFile, 'utf-8');
    } catch {
      return undefined;
    }
  }

  private slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
  }

  private extractDescription(content: string): string {
    // Extract first paragraph or summary from content
    const lines = content.split('\n');
    const paragraphs: string[] = [];
    let currentParagraph: string[] = [];

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) {
        if (currentParagraph.length > 0) {
          paragraphs.push(currentParagraph.join(' '));
          currentParagraph = [];
        }
      } else if (!trimmed.startsWith('#') && !trimmed.startsWith('- [') && !trimmed.startsWith('##')) {
        currentParagraph.push(trimmed);
      }
    }

    if (currentParagraph.length > 0) {
      paragraphs.push(currentParagraph.join(' '));
    }

    return paragraphs.join(' ').trim();
  }

  private determineStatus(
    sourceStatus?: string,
    subtasks?: Array<{ name: string; status: string }>,
    isArchived: boolean = false,
  ): string {
    if (isArchived) {
      return 'completed';
    }

    if (sourceStatus) {
      const normalized = sourceStatus.toLowerCase();
      if (['draft', 'planned', 'planning', 'proposal'].includes(normalized)) {
        return 'planning';
      }
      if (['active', 'in-progress', 'in_progress', 'started', 'wip'].includes(normalized)) {
        return 'in_progress';
      }
      if (['accepted', 'archived', 'completed', 'complete', 'done'].includes(normalized)) {
        return 'completed';
      }
    }

    if (!subtasks || subtasks.length === 0) {
      return isArchived ? 'completed' : 'planning';
    }
    const completedCount = subtasks.filter(t => t.status === 'completed').length;
    if (completedCount === 0) {
      return 'planning';
    }
    if (completedCount === subtasks.length) {
      return 'completed';
    }
    return 'in_progress';
  }

  private async ensureWorkflowSkeleton(targetPath: string): Promise<void> {
    if (this.ensuredSkeletonRoots.has(targetPath)) {
      return;
    }

    await this.writeFileIfMissing(
      path.join(targetPath, '.trellis', 'workflow.md'),
      TRELLIS_WORKFLOW_TEMPLATE,
    );
    await this.writeFileIfMissing(
      path.join(targetPath, '.trellis', 'spec', 'backend', 'index.md'),
      TRELLIS_BACKEND_INDEX_TEMPLATE,
    );
    await this.writeFileIfMissing(
      path.join(targetPath, '.trellis', 'spec', 'frontend', 'index.md'),
      TRELLIS_FRONTEND_INDEX_TEMPLATE,
    );
    await this.writeFileIfMissing(
      path.join(targetPath, '.trellis', 'spec', 'guides', 'index.md'),
      TRELLIS_GUIDES_INDEX_TEMPLATE,
    );

    this.ensuredSkeletonRoots.add(targetPath);
  }

  private async writeFileIfMissing(filePath: string, content: string): Promise<void> {
    try {
      await fs.access(filePath);
    } catch {
      await fs.mkdir(path.dirname(filePath), { recursive: true });
      await fs.writeFile(filePath, content);
    }
  }

  private resolveTaskSlug(entity: CoreEntity): string {
    const sourceSlug = typeof entity.metadata.sourceSlug === 'string'
      ? entity.metadata.sourceSlug
      : null;
    return this.slugify(sourceSlug || entity.name);
  }

  private resolveTaskTitle(entity: CoreEntity): string {
    return typeof entity.metadata.sourceTitle === 'string'
      ? entity.metadata.sourceTitle
      : entity.name;
  }

  private resolveTaskDescription(entity: CoreEntity): string {
    if (typeof entity.metadata.sourceDescription === 'string' && entity.metadata.sourceDescription.trim()) {
      return entity.metadata.sourceDescription.trim();
    }
    if (typeof entity.metadata.sourceTaskSummary === 'string' && entity.metadata.sourceTaskSummary.trim()) {
      return entity.metadata.sourceTaskSummary.trim();
    }
    return this.extractDescription(entity.content);
  }

  private resolveAssignee(entity: CoreEntity): string {
    if (typeof entity.metadata.sourceOwner === 'string' && entity.metadata.sourceOwner !== 'TBD') {
      return entity.metadata.sourceOwner;
    }
    return '';
  }

  private resolveSourceExtendedType(entity: CoreEntity): string {
    return typeof entity.metadata.sourceExtendedType === 'string'
      ? entity.metadata.sourceExtendedType
      : typeof entity.metadata.convertedFrom === 'string'
        ? entity.metadata.convertedFrom
        : entity.extendedType;
  }

  private resolveSourceCreatedAt(entity: CoreEntity): string {
    if (typeof entity.metadata.createdAt === 'string' && entity.metadata.createdAt) {
      return entity.metadata.createdAt;
    }
    if (typeof entity.metadata.date === 'string' && entity.metadata.date) {
      return `${entity.metadata.date}T00:00:00.000Z`;
    }
    return entity.createdAt;
  }

  private resolveSourceUpdatedAt(entity: CoreEntity): string | null {
    if (typeof entity.metadata.updatedAt === 'string' && entity.metadata.updatedAt) {
      return entity.metadata.updatedAt;
    }
    return entity.updatedAt || null;
  }

  private resolveSourceArchivedAt(entity: CoreEntity): string | null {
    if (typeof entity.metadata.archivedAt === 'string' && entity.metadata.archivedAt) {
      return entity.metadata.archivedAt;
    }
    return null;
  }

  private resolveCompletedAt(entity: CoreEntity): string | null {
    return this.resolveSourceArchivedAt(entity)
      ?? this.resolveSourceUpdatedAt(entity)
      ?? this.resolveSourceCreatedAt(entity);
  }

  private resolveArchiveMonth(entity: CoreEntity, sourceCreatedAt: string): string {
    const sourceArchivedAt = this.resolveSourceArchivedAt(entity);
    if (sourceArchivedAt && sourceArchivedAt.length >= 7) {
      return sourceArchivedAt.slice(0, 7);
    }
    if (sourceCreatedAt.length >= 7) {
      return sourceCreatedAt.slice(0, 7);
    }
    return new Date().toISOString().slice(0, 7);
  }

  private buildTaskDirectoryName(taskSlug: string, sourceCreatedAt: string): string {
    const date = this.extractDateOnly(sourceCreatedAt);
    if (!date) {
      return taskSlug;
    }
    return `${date.slice(5, 7)}-${date.slice(8, 10)}-${taskSlug}`;
  }

  private extractDateOnly(value: string): string | null {
    const match = value.match(/(\d{4}-\d{2}-\d{2})/);
    return match ? match[1] : null;
  }

  private async writeTaskContextFiles(
    taskDir: string,
    implementEntries: Array<{ file: string; reason: string }>,
  ): Promise<void> {
    await this.writeJsonl(path.join(taskDir, 'implement.jsonl'), implementEntries);
    await this.writeJsonl(path.join(taskDir, 'check.jsonl'), DEFAULT_CHECK_CONTEXT);
    await this.writeJsonl(path.join(taskDir, 'debug.jsonl'), DEFAULT_DEBUG_CONTEXT);
  }

  private async resolveTaskContext(
    targetPath: string,
    entity: CoreEntity,
  ): Promise<{
    devType: 'backend' | 'frontend' | 'fullstack';
    implementEntries: Array<{ file: string; reason: string }>;
  }> {
    const repoDevType = await this.detectProjectDevType(targetPath);
    const signalHaystack = buildEntitySignalHaystack(entity);
    const needsFrontendContext = hasUiSignals(signalHaystack);
    const devType = needsFrontendContext
      ? repoDevType === 'frontend'
        ? 'frontend'
        : 'fullstack'
      : repoDevType;

    const implementEntries = [{ file: '.trellis/workflow.md', reason: 'Project workflow and conventions' }];
    if (devType !== 'frontend') {
      implementEntries.push({
        file: '.trellis/spec/backend/index.md',
        reason: 'Backend development guide',
      });
    }
    if (devType !== 'backend') {
      implementEntries.push({
        file: '.trellis/spec/frontend/index.md',
        reason: 'Frontend or interaction-surface guide',
      });
    }
    if (devType === 'fullstack') {
      implementEntries.push({
        file: '.trellis/spec/guides/cross-layer-thinking-guide.md',
        reason: 'Task spans runtime and interaction-layer behavior',
      });
    }

    return { devType, implementEntries };
  }

  private buildPreservedSourceFiles(entity: CoreEntity): Record<string, string> {
    const files: Record<string, string> = {};

    if (typeof entity.metadata.tasksContent === 'string' && entity.metadata.tasksContent.trim()) {
      files.tasksMd = 'source-tasks.md';
    }
    if (typeof entity.metadata.changeManifestContent === 'string' && entity.metadata.changeManifestContent.trim()) {
      files.manifestYaml = 'source-manifest.yaml';
    }
    if (typeof entity.metadata.designContent === 'string' && entity.metadata.designContent.trim()) {
      files.designMd = 'design.md';
    }

    return files;
  }

  private async writePreservedSourceArtifacts(taskDir: string, entity: CoreEntity): Promise<void> {
    if (typeof entity.metadata.tasksContent === 'string' && entity.metadata.tasksContent.trim()) {
      await fs.writeFile(path.join(taskDir, 'source-tasks.md'), entity.metadata.tasksContent);
    }
    if (typeof entity.metadata.changeManifestContent === 'string' && entity.metadata.changeManifestContent.trim()) {
      await fs.writeFile(path.join(taskDir, 'source-manifest.yaml'), entity.metadata.changeManifestContent);
    }
  }

  private async writeJsonl(filePath: string, entries: Array<{ file: string; reason: string }>): Promise<void> {
    await fs.writeFile(
      filePath,
      `${entries.map(entry => JSON.stringify(entry)).join('\n')}\n`,
    );
  }

  private async detectProjectDevType(targetPath: string): Promise<'backend' | 'frontend' | 'fullstack'> {
    const cached = this.detectedDevTypes.get(targetPath);
    if (cached) {
      return cached;
    }

    const markers = { backend: false, frontend: false };
    await this.scanProjectFiles(targetPath, 0, markers);

    const detected = markers.backend && markers.frontend
      ? 'fullstack'
      : markers.frontend
        ? 'frontend'
        : 'backend';
    this.detectedDevTypes.set(targetPath, detected);
    return detected;
  }

  private async scanProjectFiles(
    directory: string,
    depth: number,
    markers: { backend: boolean; frontend: boolean },
  ): Promise<void> {
    if (depth > 4 || (markers.backend && markers.frontend)) {
      return;
    }

    let entries: string[];
    try {
      entries = await fs.readdir(directory);
    } catch {
      return;
    }

    for (const entry of entries) {
      if (SKIPPED_SCAN_DIRECTORIES.has(entry)) {
        continue;
      }

      const fullPath = path.join(directory, entry);
      let stat;
      try {
        stat = await fs.stat(fullPath);
      } catch {
        continue;
      }

      if (stat.isDirectory()) {
        await this.scanProjectFiles(fullPath, depth + 1, markers);
        if (markers.backend && markers.frontend) {
          return;
        }
        continue;
      }

      const extension = path.extname(entry).toLowerCase();
      if (['.tsx', '.jsx', '.vue', '.svelte', '.css', '.scss', '.html'].includes(extension)) {
        markers.frontend = true;
      } else if ([
        '.c',
        '.cc',
        '.cpp',
        '.cs',
        '.go',
        '.java',
        '.js',
        '.kt',
        '.mjs',
        '.mts',
        '.php',
        '.py',
        '.rb',
        '.rs',
        '.sh',
        '.swift',
        '.ts',
      ].includes(extension)) {
        markers.backend = true;
      }
    }
  }

  private async detectBaseBranch(targetPath: string): Promise<string | null> {
    if (this.detectedBaseBranches.has(targetPath)) {
      return this.detectedBaseBranches.get(targetPath) ?? null;
    }

    const gitDir = await this.resolveGitDir(targetPath);
    if (!gitDir) {
      this.detectedBaseBranches.set(targetPath, null);
      return null;
    }

    try {
      const head = (await fs.readFile(path.join(gitDir, 'HEAD'), 'utf-8')).trim();
      const match = head.match(/^ref:\s+refs\/heads\/(.+)$/);
      const branch = match ? match[1] : null;
      this.detectedBaseBranches.set(targetPath, branch);
      return branch;
    } catch {
      this.detectedBaseBranches.set(targetPath, null);
      return null;
    }
  }

  private async resolveGitDir(targetPath: string): Promise<string | null> {
    const gitPath = path.join(targetPath, '.git');
    try {
      const stat = await fs.stat(gitPath);
      if (stat.isDirectory()) {
        return gitPath;
      }
      const gitFile = await fs.readFile(gitPath, 'utf-8');
      const match = gitFile.match(/^gitdir:\s*(.+)\s*$/m);
      if (!match) {
        return null;
      }
      return path.resolve(targetPath, match[1]);
    } catch {
      return null;
    }
  }
}
