import * as fs from 'fs/promises';
import * as path from 'path';
import { parse as parseYaml } from 'yaml';
import { loadProjectConfig } from '../../cli/utils/project-config.js';
import { hasStructuredTaskContent, parseTaskStructure } from '../framework/task-structure.js';
import { hasUiSignals } from '../framework/task-signals.js';
import { getProjectEnhancedAnalysisPath, getProjectPostprocessContextPath, getProjectPreprocessContextPath } from '../skill/index.js';
import type { EnhancedAnalysisFile, PostprocessContextFile, PreprocessContextFile } from '../skill/project-runtime.js';

type Severity = 'error' | 'warning' | 'info';

export interface ValidationIssue {
  severity: Severity;
  code: string;
  message: string;
  path?: string;
}

export interface ValidationResult {
  success: boolean;
  issues: ValidationIssue[];
  summary: {
    sourceFramework?: string;
    targetFramework?: string;
    checkedTasks: number;
    checkedRelations: number;
  };
}

interface TrellisTaskDirectory {
  dirPath: string;
  archived: boolean;
}

const WORKFLOW_BASELINE_MARKER = 'Generated by Transpec as a minimum Trellis runtime skeleton.';
const BACKEND_INDEX_BASELINE_MARKER = 'Generated baseline Trellis backend index.';
const FRONTEND_INDEX_BASELINE_MARKER = 'Generated baseline Trellis frontend index.';
const GUIDES_INDEX_BASELINE_MARKER = 'Generated baseline Trellis guide index.';

const REQUIRED_TASK_FIELDS = [
  'id',
  'name',
  'title',
  'description',
  'status',
  'creator',
  'assignee',
  'createdAt',
  'base_branch',
  'current_phase',
  'next_action',
  'dev_type',
  'meta',
] as const;
const REQUIRED_TASK_META_FIELDS = [
  'originalExtendedType',
  'sourceFramework',
  'sourcePath',
  'sourceCreatedAt',
  'sourceStatus',
  'importedAt',
  'isArchived',
] as const;

export async function validateConvertedProject(projectPath: string): Promise<ValidationResult> {
  const issues: ValidationIssue[] = [];
  let config;

  try {
    config = await loadProjectConfig(projectPath);
  } catch (error) {
    issues.push({
      severity: 'error',
      code: 'missing_config',
      message: `Failed to load .transpec/config.yaml: ${(error as Error).message}`,
      path: path.join(projectPath, '.transpec', 'config.yaml'),
    });
    return {
      success: false,
      issues,
      summary: { checkedTasks: 0, checkedRelations: 0 },
    };
  }

  const sourceFramework = config.project?.sourceFramework;
  const targetFramework = config.project?.targetFramework;

  if (!sourceFramework || !targetFramework) {
    issues.push({
      severity: 'error',
      code: 'missing_framework_config',
      message: 'Source and target frameworks must be configured in .transpec/config.yaml.',
      path: path.join(projectPath, '.transpec', 'config.yaml'),
    });
    return {
      success: false,
      issues,
      summary: { sourceFramework, targetFramework, checkedTasks: 0, checkedRelations: 0 },
    };
  }

  if (sourceFramework === 'openspec' && targetFramework === 'trellis') {
    const details = await validateOpenSpecToTrellis(projectPath, issues);
    return {
      success: !issues.some(issue => issue.severity === 'error'),
      issues,
      summary: {
        sourceFramework,
        targetFramework,
        checkedTasks: details.checkedTasks,
        checkedRelations: details.checkedRelations,
      },
    };
  }

  issues.push({
    severity: 'warning',
    code: 'unsupported_validation_target',
    message: `No framework-specific validation checks are implemented for ${sourceFramework} -> ${targetFramework} yet.`,
  });
  return {
    success: !issues.some(issue => issue.severity === 'error'),
    issues,
    summary: { sourceFramework, targetFramework, checkedTasks: 0, checkedRelations: 0 },
  };
}

async function validateOpenSpecToTrellis(
  projectPath: string,
  issues: ValidationIssue[],
): Promise<{ checkedTasks: number; checkedRelations: number }> {
  const preprocessContextPath = getProjectPreprocessContextPath(projectPath);
  const enhancedAnalysisPath = getProjectEnhancedAnalysisPath(projectPath);
  const postprocessContextPath = getProjectPostprocessContextPath(projectPath);

  const preprocessContext = await readOptionalJson<PreprocessContextFile>(preprocessContextPath, issues, 'missing_preprocess_context');
  const enhancedAnalysis = await readOptionalJson<EnhancedAnalysisFile>(enhancedAnalysisPath, issues, 'missing_enhanced_analysis');
  await readOptionalJson<PostprocessContextFile>(postprocessContextPath, issues, 'missing_postprocess_context');

  if (preprocessContext) {
    if (preprocessContext.relationCount <= 0 || preprocessContext.relations.length <= 0) {
      issues.push({
        severity: 'error',
        code: 'missing_relations',
        message: 'preprocess-context.json does not contain any exported relations.',
        path: preprocessContextPath,
      });
    }

    if (enhancedAnalysis) {
      const enhancedIds = new Set(Object.keys(enhancedAnalysis.entities));
      const matchedEnhancedIds = preprocessContext.entities.filter(entity => enhancedIds.has(entity.id));

      if (enhancedIds.size > 0 && matchedEnhancedIds.length === 0) {
        issues.push({
          severity: 'error',
          code: 'enhanced_analysis_id_mismatch',
          message: 'enhanced-analysis.json exists but none of its entity IDs match the current preprocess output. Re-run enhanced analysis after preprocess.',
          path: enhancedAnalysisPath,
        });
      }

      for (const entity of preprocessContext.entities) {
        if (enhancedIds.has(entity.id) && !entity.hasEnhancedAnalysis) {
          issues.push({
            severity: 'error',
            code: 'enhanced_analysis_unsynced',
            message: `Entity "${entity.name}" has enhanced analysis on disk but preprocess-context.json still marks it false.`,
            path: preprocessContextPath,
          });
        }
      }
    }
  }

  await ensureFileExists(path.join(projectPath, '.trellis', 'workflow.md'), issues, 'missing_workflow');
  await ensureFileExists(path.join(projectPath, '.trellis', 'spec', 'backend', 'index.md'), issues, 'missing_backend_index');
  await ensureFileExists(path.join(projectPath, '.trellis', 'spec', 'frontend', 'index.md'), issues, 'missing_frontend_index');
  await ensureFileExists(path.join(projectPath, '.trellis', 'spec', 'guides', 'index.md'), issues, 'missing_guides_index');
  await ensureFileExists(
    path.join(projectPath, '.trellis', 'spec', 'guides', 'repository-and-conversion-state.md'),
    issues,
    'missing_repository_state_guide',
  );
  await validateGroundedDocs(projectPath, issues);
  await validateBootstrapState(projectPath, issues);

  const groundedSpecCount = await countGroundedSpecs(path.join(projectPath, '.trellis', 'spec'));
  if (groundedSpecCount <= 0) {
    issues.push({
      severity: 'error',
      code: 'missing_grounded_specs',
      message: 'No grounded Trellis spec documents were generated under .trellis/spec/.',
      path: path.join(projectPath, '.trellis', 'spec'),
    });
  }

  const openspecCounts = await countOpenSpecSource(projectPath);
  const trellisCounts = await countTrellisOutputs(projectPath);
  if (openspecCounts.specCount !== trellisCounts.legacySpecCount) {
    issues.push({
      severity: 'error',
      code: 'legacy_spec_count_mismatch',
      message: `Expected ${openspecCounts.specCount} legacy specs but found ${trellisCounts.legacySpecCount}.`,
      path: path.join(projectPath, '.trellis', 'legacy', 'specs'),
    });
  }
  if (openspecCounts.archivedChangeCount !== trellisCounts.archivedTaskCount) {
    issues.push({
      severity: 'error',
      code: 'archived_task_count_mismatch',
      message: `Expected ${openspecCounts.archivedChangeCount} archived Trellis tasks but found ${trellisCounts.archivedTaskCount}.`,
      path: path.join(projectPath, '.trellis', 'tasks', 'archive'),
    });
  }

  const taskDirectories = await collectTaskDirectories(path.join(projectPath, '.trellis', 'tasks'));
  for (const task of taskDirectories) {
    await validateTaskDirectory(task, projectPath, issues);
  }

  return {
    checkedTasks: taskDirectories.length,
    checkedRelations: preprocessContext?.relationCount ?? 0,
  };
}

async function validateTaskDirectory(
  task: TrellisTaskDirectory,
  projectPath: string,
  issues: ValidationIssue[],
): Promise<void> {
  const taskJsonPath = path.join(task.dirPath, 'task.json');
  const taskJson = await readOptionalJson<Record<string, unknown>>(taskJsonPath, issues, 'missing_task_json');
  const prdPath = path.join(task.dirPath, 'prd.md');
  const implementPath = path.join(task.dirPath, 'implement.jsonl');
  const checkPath = path.join(task.dirPath, 'check.jsonl');
  const debugPath = path.join(task.dirPath, 'debug.jsonl');

  await ensureFileExists(prdPath, issues, 'missing_prd');
  await ensureFileExists(implementPath, issues, 'missing_implement_context');
  await ensureFileExists(checkPath, issues, 'missing_check_context');
  await ensureFileExists(debugPath, issues, 'missing_debug_context');

  if (!taskJson) {
    return;
  }

  for (const field of REQUIRED_TASK_FIELDS) {
    if (!(field in taskJson)) {
      issues.push({
        severity: 'error',
        code: 'missing_task_field',
        message: `Task ${task.dirPath} is missing required field "${field}".`,
        path: taskJsonPath,
      });
    }
  }

  const meta = typeof taskJson.meta === 'object' && taskJson.meta !== null
    ? taskJson.meta as Record<string, unknown>
    : null;
  if (!meta) {
    issues.push({
      severity: 'error',
      code: 'missing_task_meta',
      message: `Task ${task.dirPath} is missing task.json.meta.`,
      path: taskJsonPath,
    });
    return;
  }

  for (const field of REQUIRED_TASK_META_FIELDS) {
    if (!(field in meta)) {
      issues.push({
        severity: 'error',
        code: 'missing_task_meta_field',
        message: `Task ${task.dirPath} is missing meta.${field}.`,
        path: taskJsonPath,
      });
    }
  }

  if (typeof taskJson.description === 'string' && taskJson.description.trim().endsWith('...')) {
    issues.push({
      severity: 'warning',
      code: 'truncated_description',
      message: `Task ${task.dirPath} still has an ellipsis-truncated description.`,
      path: taskJsonPath,
    });
  }

  const metaSourcePath = typeof meta.sourcePath === 'string' ? meta.sourcePath : '';
  const metaArchived = Boolean(meta.isArchived);
  if (task.archived !== metaArchived) {
    issues.push({
      severity: 'error',
      code: 'archive_location_mismatch',
      message: `Task ${task.dirPath} archive placement does not match meta.isArchived=${metaArchived}.`,
      path: taskJsonPath,
    });
  }
  if (!task.archived && metaSourcePath.includes('/changes/archive/')) {
    issues.push({
      severity: 'error',
      code: 'archived_source_in_active_pool',
      message: `Archived OpenSpec source was emitted into the active Trellis task pool: ${task.dirPath}.`,
      path: taskJsonPath,
    });
  }
  if (typeof meta.originalExtendedType === 'string' && metaSourcePath.includes('/changes/') && meta.originalExtendedType !== 'change') {
    issues.push({
      severity: 'error',
      code: 'wrong_original_extended_type',
      message: `Task ${task.dirPath} should preserve originalExtendedType="change".`,
      path: taskJsonPath,
    });
  }
  if (typeof taskJson.createdAt === 'string' && typeof meta.sourceCreatedAt === 'string' && taskJson.createdAt !== meta.sourceCreatedAt) {
    issues.push({
      severity: 'warning',
      code: 'created_at_mismatch',
      message: `Task ${task.dirPath} createdAt does not match meta.sourceCreatedAt.`,
      path: taskJsonPath,
    });
  }

  validateTaskTimeline(taskJson, meta, taskJsonPath, issues);

  const prdContent = await readOptionalText(prdPath);
  const implementEntries = await readJsonlEntries(implementPath);
  const checkEntries = await readJsonlEntries(checkPath);
  const debugEntries = await readJsonlEntries(debugPath);
  validateTaskContext(task, taskJson, meta, prdContent, implementEntries, taskJsonPath, issues);
  validateTaskLifecycle(task, taskJson, meta, taskJsonPath, issues);
  await validateTaskContextReferences(projectPath, implementPath, implementEntries, issues);
  await validateTaskContextReferences(projectPath, checkPath, checkEntries, issues);
  await validateTaskContextReferences(projectPath, debugPath, debugEntries, issues);
  await validatePreservedSourceArtifacts(task, meta, taskJsonPath, issues);
  await validateStructuredTaskMetadata(task, meta, taskJsonPath, issues);
  await validateSourceTimestampTrust(task, meta, issues);
}

async function readOptionalJson<T>(
  filePath: string,
  issues: ValidationIssue[],
  code: string,
): Promise<T | null> {
  try {
    const content = await fs.readFile(filePath, 'utf-8');
    return JSON.parse(content) as T;
  } catch (error) {
    issues.push({
      severity: 'error',
      code,
      message: `Failed to read ${filePath}: ${(error as Error).message}`,
      path: filePath,
    });
    return null;
  }
}

async function ensureFileExists(filePath: string, issues: ValidationIssue[], code: string): Promise<void> {
  try {
    await fs.access(filePath);
  } catch {
    issues.push({
      severity: 'error',
      code,
      message: `Missing required file: ${filePath}`,
      path: filePath,
    });
  }
}

async function validateBootstrapState(projectPath: string, issues: ValidationIssue[]): Promise<void> {
  const scriptsPath = path.join(projectPath, '.trellis', 'scripts');
  const guidePath = path.join(projectPath, '.trellis', 'spec', 'guides', 'repository-and-conversion-state.md');
  const hasScripts = await pathExists(scriptsPath);
  const guideContent = await readOptionalText(guidePath);

  if (!hasScripts) {
    issues.push({
      severity: 'info',
      code: 'trellis_bootstrap_follow_up',
      message: 'Only the minimum Trellis runtime skeleton is present. Run `trellis update` and then `trellis init` if you need the full Trellis workflow/tooling bundle.',
      path: scriptsPath,
    });
  }

  if (hasScripts && guideContent && /there is no\s+`?\.trellis\/scripts\/`?\s+directory/i.test(guideContent)) {
    issues.push({
      severity: 'warning',
      code: 'stale_repository_state_guide',
      message: 'repository-and-conversion-state.md still claims `.trellis/scripts/` is missing even though it exists now. Re-run `transpec postprocess`.',
      path: guidePath,
    });
  }
}

async function validateGroundedDocs(projectPath: string, issues: ValidationIssue[]): Promise<void> {
  const workflowPath = path.join(projectPath, '.trellis', 'workflow.md');
  const backendIndexPath = path.join(projectPath, '.trellis', 'spec', 'backend', 'index.md');
  const frontendIndexPath = path.join(projectPath, '.trellis', 'spec', 'frontend', 'index.md');
  const guidesIndexPath = path.join(projectPath, '.trellis', 'spec', 'guides', 'index.md');

  const workflowContent = await readOptionalText(workflowPath);
  if (workflowContent?.includes(WORKFLOW_BASELINE_MARKER)) {
    issues.push({
      severity: 'warning',
      code: 'baseline_workflow_unresolved',
      message: 'workflow.md still looks like the minimum runtime skeleton instead of a grounded converted workflow.',
      path: workflowPath,
    });
  }

  await validateSpecIndex(projectPath, backendIndexPath, BACKEND_INDEX_BASELINE_MARKER, issues);
  await validateSpecIndex(projectPath, frontendIndexPath, FRONTEND_INDEX_BASELINE_MARKER, issues);
  await validateSpecIndex(projectPath, guidesIndexPath, GUIDES_INDEX_BASELINE_MARKER, issues);
}

async function validateSpecIndex(
  projectPath: string,
  indexPath: string,
  baselineMarker: string,
  issues: ValidationIssue[],
): Promise<void> {
  const content = await readOptionalText(indexPath);
  if (!content) {
    return;
  }

  if (content.includes(baselineMarker)) {
    issues.push({
      severity: 'warning',
      code: 'baseline_spec_index_unresolved',
      message: `Spec index ${indexPath} still looks like a baseline skeleton instead of grounded conversion output.`,
      path: indexPath,
    });
  }

  await validateMarkdownReferences(projectPath, indexPath, content, issues);
}

async function validateMarkdownReferences(
  projectPath: string,
  sourceFile: string,
  content: string,
  issues: ValidationIssue[],
): Promise<void> {
  const sourceDir = path.dirname(sourceFile);
  const refs = extractMarkdownReferences(content);

  for (const ref of refs) {
    const resolved = resolveReferencePath(projectPath, sourceDir, ref);
    if (!resolved || await pathExists(resolved)) {
      continue;
    }

    issues.push({
      severity: 'warning',
      code: 'broken_doc_reference',
      message: `${sourceFile} references missing markdown artifact "${ref}".`,
      path: sourceFile,
    });
  }
}

function validateTaskTimeline(
  taskJson: Record<string, unknown>,
  meta: Record<string, unknown>,
  taskJsonPath: string,
  issues: ValidationIssue[],
): void {
  const createdAt = typeof taskJson.createdAt === 'string' ? taskJson.createdAt : null;
  const completedAt = typeof taskJson.completedAt === 'string' ? taskJson.completedAt : null;
  if (createdAt && completedAt && createdAt > completedAt) {
    issues.push({
      severity: 'error',
      code: 'impossible_task_timeline',
      message: `Task ${taskJsonPath} has createdAt later than completedAt.`,
      path: taskJsonPath,
    });
  }

  const sourceCreatedAt = typeof meta.sourceCreatedAt === 'string' ? meta.sourceCreatedAt : null;
  const sourceArchivedAt = typeof meta.sourceArchivedAt === 'string' ? meta.sourceArchivedAt : null;
  if (sourceCreatedAt && sourceArchivedAt && sourceCreatedAt > sourceArchivedAt) {
    issues.push({
      severity: 'error',
      code: 'impossible_source_timeline',
      message: `Task ${taskJsonPath} preserves a source timeline where sourceCreatedAt is later than sourceArchivedAt.`,
      path: taskJsonPath,
    });
  }
}

function validateTaskLifecycle(
  task: TrellisTaskDirectory,
  taskJson: Record<string, unknown>,
  meta: Record<string, unknown>,
  taskJsonPath: string,
  issues: ValidationIssue[],
): void {
  const status = typeof taskJson.status === 'string' ? taskJson.status : null;
  const completedAt = typeof taskJson.completedAt === 'string' ? taskJson.completedAt : null;
  const currentPhase = typeof taskJson.current_phase === 'number' ? taskJson.current_phase : null;
  const nextAction = Array.isArray(taskJson.next_action) ? taskJson.next_action : [];
  const metaArchived = Boolean(meta.isArchived);

  if (metaArchived && status !== 'completed') {
    issues.push({
      severity: 'warning',
      code: 'archived_task_not_completed',
      message: `Archived task ${task.dirPath} is not marked completed in task.json.`,
      path: taskJsonPath,
    });
  }

  if (status === 'completed' && !completedAt) {
    issues.push({
      severity: 'warning',
      code: 'completed_task_missing_completed_at',
      message: `Completed task ${task.dirPath} is missing completedAt.`,
      path: taskJsonPath,
    });
  }

  if (status === 'completed' && nextAction.length > 0) {
    issues.push({
      severity: 'warning',
      code: 'completed_task_has_next_actions',
      message: `Completed task ${task.dirPath} still has next_action entries.`,
      path: taskJsonPath,
    });
  }

  if (status === 'completed' && currentPhase === 0) {
    issues.push({
      severity: 'warning',
      code: 'completed_task_default_phase',
      message: `Completed task ${task.dirPath} still has the default current_phase=0.`,
      path: taskJsonPath,
    });
  }
}

function validateTaskContext(
  task: TrellisTaskDirectory,
  taskJson: Record<string, unknown>,
  meta: Record<string, unknown>,
  prdContent: string | null,
  implementEntries: Array<{ file?: string; reason?: string }>,
  taskJsonPath: string,
  issues: ValidationIssue[],
): void {
  const needsFrontendContext = hasUiSignals(
    taskJson.title,
    taskJson.description,
    prdContent,
    meta.sourcePath,
    meta.preservedSourceFiles,
  );
  if (!needsFrontendContext) {
    return;
  }

  if (taskJson.dev_type === 'backend' || taskJson.dev_type == null) {
    issues.push({
      severity: 'warning',
      code: 'ui_task_dev_type_degraded',
      message: `Task ${task.dirPath} looks like a UI/TUI/setup workflow but dev_type is ${String(taskJson.dev_type)}.`,
      path: taskJsonPath,
    });
  }

  const hasFrontendContext = implementEntries.some(entry => typeof entry.file === 'string' && entry.file.startsWith('.trellis/spec/frontend/'));
  if (!hasFrontendContext) {
    issues.push({
      severity: 'warning',
      code: 'ui_task_missing_frontend_context',
      message: `Task ${task.dirPath} looks like a UI/TUI/setup workflow but implement.jsonl does not include any frontend Trellis context.`,
      path: path.join(task.dirPath, 'implement.jsonl'),
    });
  }
}

async function validatePreservedSourceArtifacts(
  task: TrellisTaskDirectory,
  meta: Record<string, unknown>,
  taskJsonPath: string,
  issues: ValidationIssue[],
): Promise<void> {
  const preservedFiles = getRecord(meta.preservedSourceFiles);
  const sourcePath = typeof meta.sourcePath === 'string' ? meta.sourcePath : null;
  const sourceDir = sourcePath ? path.dirname(sourcePath) : null;
  const sourceTasksPath = sourceDir ? path.join(sourceDir, 'tasks.md') : null;
  const sourceManifestPath = sourceDir ? path.join(sourceDir, '.openspec.yaml') : null;
  const sourceDesignPath = sourceDir ? path.join(sourceDir, 'design.md') : null;

  if (sourceTasksPath && await pathExists(sourceTasksPath)) {
    const preservedTaskFile = typeof preservedFiles?.tasksMd === 'string'
      ? path.join(task.dirPath, preservedFiles.tasksMd)
      : path.join(task.dirPath, 'source-tasks.md');
    if (!await pathExists(preservedTaskFile)) {
      issues.push({
        severity: 'error',
        code: 'missing_preserved_tasks_artifact',
        message: `Task ${task.dirPath} lost source tasks.md content during conversion; expected preserved artifact.`,
        path: taskJsonPath,
      });
    }
  }

  if (sourceManifestPath && await pathExists(sourceManifestPath)) {
    const preservedManifestFile = typeof preservedFiles?.manifestYaml === 'string'
      ? path.join(task.dirPath, preservedFiles.manifestYaml)
      : path.join(task.dirPath, 'source-manifest.yaml');
    if (!await pathExists(preservedManifestFile)) {
      issues.push({
        severity: 'warning',
        code: 'missing_preserved_manifest_artifact',
        message: `Task ${task.dirPath} did not preserve the raw OpenSpec manifest as a target artifact.`,
        path: taskJsonPath,
      });
    }
  }

  if (sourceDesignPath && await pathExists(sourceDesignPath) && !await pathExists(path.join(task.dirPath, 'design.md'))) {
    issues.push({
      severity: 'error',
      code: 'missing_preserved_design_artifact',
      message: `Task ${task.dirPath} is missing design.md even though the source OpenSpec change had one.`,
      path: taskJsonPath,
    });
  }
}

async function validateStructuredTaskMetadata(
  task: TrellisTaskDirectory,
  meta: Record<string, unknown>,
  taskJsonPath: string,
  issues: ValidationIssue[],
): Promise<void> {
  const sourcePath = typeof meta.sourcePath === 'string' ? meta.sourcePath : null;
  if (!sourcePath) {
    return;
  }

  const sourceTasksPath = path.join(path.dirname(sourcePath), 'tasks.md');
  if (!await pathExists(sourceTasksPath)) {
    return;
  }

  const tasksContent = await readOptionalText(sourceTasksPath);
  if (!tasksContent) {
    return;
  }

  const parsedTasks = parseTaskStructure(tasksContent);
  if (!hasStructuredTaskContent(parsedTasks)) {
    return;
  }

  const missingPieces: string[] = [];
  if (parsedTasks.summary && typeof meta.sourceTaskSummary !== 'string') {
    missingPieces.push('summary');
  }
  if (parsedTasks.acceptanceCriteria.length > 0 && !hasNonEmptyStringArray(meta.sourceAcceptanceCriteria)) {
    missingPieces.push('acceptance criteria');
  }
  if (parsedTasks.followUpSuggestions.length > 0 && !hasNonEmptyStringArray(meta.sourceFollowUpSuggestions)) {
    missingPieces.push('follow-up suggestions');
  }
  if (parsedTasks.estimates.length > 0 && !hasStructuredEstimateArray(meta.sourceTaskEstimates)) {
    missingPieces.push('estimates');
  }
  if (parsedTasks.sections.length > 0 && !hasStructuredSectionArray(meta.sourceTaskSections)) {
    missingPieces.push('structured sections');
  }

  if (missingPieces.length === 0) {
    return;
  }

  issues.push({
    severity: 'warning',
    code: 'missing_structured_tasks_metadata',
    message: `Task ${task.dirPath} did not preserve structured tasks.md metadata for: ${missingPieces.join(', ')}.`,
    path: taskJsonPath,
  });
}

async function validateSourceTimestampTrust(
  task: TrellisTaskDirectory,
  meta: Record<string, unknown>,
  issues: ValidationIssue[],
): Promise<void> {
  const sourcePath = typeof meta.sourcePath === 'string' ? meta.sourcePath : null;
  if (!sourcePath) {
    return;
  }

  const manifestPath = path.join(path.dirname(sourcePath), '.openspec.yaml');
  if (!await pathExists(manifestPath)) {
    return;
  }

  const manifestContent = await readOptionalText(manifestPath);
  if (!manifestContent) {
    return;
  }

  const manifest = parseYaml(manifestContent);
  if (!manifest || typeof manifest !== 'object' || Array.isArray(manifest)) {
    return;
  }

  const record = manifest as Record<string, unknown>;
  const sourceCreatedAt = typeof meta.sourceCreatedAt === 'string' ? meta.sourceCreatedAt : null;
  const sourceUpdatedAt = typeof meta.sourceUpdatedAt === 'string' ? meta.sourceUpdatedAt : null;
  const sourceArchivedAt = typeof meta.sourceArchivedAt === 'string' ? meta.sourceArchivedAt : null;
  const hasManifestUpdatedAt = typeof record.updatedAt === 'string' && record.updatedAt.trim().length > 0;
  const hasManifestArchivedAt = typeof record.archivedAt === 'string' && record.archivedAt.trim().length > 0;
  const hasManifestCompletedAt = typeof record.completedAt === 'string' && record.completedAt.trim().length > 0;

  if (!hasManifestUpdatedAt && sourceCreatedAt && sourceUpdatedAt && sourceUpdatedAt !== sourceCreatedAt) {
    issues.push({
      severity: 'warning',
      code: 'untrusted_source_updated_at',
      message: `Task ${task.dirPath} has sourceUpdatedAt=${sourceUpdatedAt} but the source manifest has no updatedAt field. This timestamp is likely converter-derived rather than source-native.`,
      path: path.join(task.dirPath, 'task.json'),
    });
  }

  if (!hasManifestArchivedAt && !hasManifestCompletedAt && sourceArchivedAt) {
    issues.push({
      severity: 'warning',
      code: 'untrusted_source_archived_at',
      message: `Task ${task.dirPath} has sourceArchivedAt=${sourceArchivedAt} but the source manifest has no archived/completed timestamp. This timestamp is likely not source-native.`,
      path: path.join(task.dirPath, 'task.json'),
    });
  }
}

async function validateTaskContextReferences(
  projectPath: string,
  contextPath: string,
  entries: Array<{ file?: string; reason?: string }>,
  issues: ValidationIssue[],
): Promise<void> {
  for (const entry of entries) {
    if (typeof entry.file !== 'string' || !entry.file.startsWith('.trellis/')) {
      continue;
    }

    const resolved = path.join(projectPath, entry.file);
    if (await pathExists(resolved)) {
      continue;
    }

    issues.push({
      severity: 'error',
      code: 'broken_task_context_reference',
      message: `${contextPath} references missing Trellis artifact "${entry.file}".`,
      path: contextPath,
    });
  }
}

function getRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function hasNonEmptyStringArray(value: unknown): boolean {
  return Array.isArray(value) && value.some(item => typeof item === 'string' && item.trim().length > 0);
}

function hasStructuredEstimateArray(value: unknown): boolean {
  return Array.isArray(value)
    && value.some(item => {
      const record = getRecord(item);
      return Boolean(record && typeof record.value === 'string' && record.value.trim().length > 0);
    });
}

function hasStructuredSectionArray(value: unknown): boolean {
  return Array.isArray(value)
    && value.some(item => {
      const record = getRecord(item);
      return Boolean(record && typeof record.title === 'string' && record.title.trim().length > 0);
    });
}

function extractMarkdownReferences(content: string): string[] {
  const references = new Set<string>();
  const markdownLinkPattern = /\(([^)\s]+\.md)\)/g;
  const inlineCodePattern = /`([^`\n]+\.md)`/g;

  for (const pattern of [markdownLinkPattern, inlineCodePattern]) {
    for (const match of content.matchAll(pattern)) {
      const ref = match[1]?.trim();
      if (!ref || ref.startsWith('http://') || ref.startsWith('https://')) {
        continue;
      }
      references.add(ref);
    }
  }

  return [...references];
}

function resolveReferencePath(projectPath: string, sourceDir: string, ref: string): string | null {
  const normalized = ref.replace(/\\/g, '/');
  if (!normalized.endsWith('.md')) {
    return null;
  }

  if (normalized.startsWith('.trellis/') || normalized.startsWith('.transpec/') || normalized.startsWith('.agents/')) {
    return path.join(projectPath, normalized);
  }

  if (normalized.startsWith('./') || normalized.startsWith('../')) {
    return path.resolve(sourceDir, normalized);
  }

  if (normalized.startsWith('/')) {
    return normalized;
  }

  return path.resolve(sourceDir, normalized);
}

async function readJsonlEntries(filePath: string): Promise<Array<{ file?: string; reason?: string }>> {
  const content = await readOptionalText(filePath);
  if (!content) {
    return [];
  }

  const entries: Array<{ file?: string; reason?: string }> = [];
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) {
      continue;
    }
    try {
      entries.push(JSON.parse(trimmed) as { file?: string; reason?: string });
    } catch {
      // Ignore malformed lines; the file existence check already covers the hard failure path.
    }
  }
  return entries;
}

async function readOptionalText(filePath: string): Promise<string | null> {
  try {
    return await fs.readFile(filePath, 'utf-8');
  } catch {
    return null;
  }
}

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function countGroundedSpecs(specRoot: string): Promise<number> {
  let count = 0;

  async function walk(currentPath: string): Promise<void> {
    let entries: string[];
    try {
      entries = await fs.readdir(currentPath);
    } catch {
      return;
    }

    for (const entry of entries) {
      const fullPath = path.join(currentPath, entry);
      const stat = await fs.stat(fullPath);
      if (stat.isDirectory()) {
        await walk(fullPath);
        continue;
      }
      if (entry.endsWith('.md') && entry !== 'index.md') {
        count += 1;
      }
    }
  }

  await walk(specRoot);
  return count;
}

async function countOpenSpecSource(projectPath: string): Promise<{ specCount: number; archivedChangeCount: number }> {
  const specsRoot = path.join(projectPath, 'openspec', 'specs');
  const archiveRoot = path.join(projectPath, 'openspec', 'changes', 'archive');
  return {
    specCount: await countImmediateVisibleDirectories(specsRoot),
    archivedChangeCount: await countImmediateVisibleDirectories(archiveRoot),
  };
}

async function countTrellisOutputs(projectPath: string): Promise<{ legacySpecCount: number; archivedTaskCount: number }> {
  const legacySpecRoot = path.join(projectPath, '.trellis', 'legacy', 'specs');
  const archiveTaskRoot = path.join(projectPath, '.trellis', 'tasks', 'archive');
  return {
    legacySpecCount: await countSpecDirectories(legacySpecRoot),
    archivedTaskCount: await countArchivedTaskDirectories(archiveTaskRoot),
  };
}

async function countImmediateVisibleDirectories(root: string): Promise<number> {
  try {
    const entries = await fs.readdir(root);
    let count = 0;
    for (const entry of entries) {
      if (entry.startsWith('.')) {
        continue;
      }
      const fullPath = path.join(root, entry);
      const stat = await fs.stat(fullPath);
      if (stat.isDirectory()) {
        count += 1;
      }
    }
    return count;
  } catch {
    return 0;
  }
}

async function countSpecDirectories(root: string): Promise<number> {
  try {
    const entries = await fs.readdir(root);
    let count = 0;
    for (const entry of entries) {
      const fullPath = path.join(root, entry);
      const stat = await fs.stat(fullPath);
      if (stat.isDirectory()) {
        count += 1;
      }
    }
    return count;
  } catch {
    return 0;
  }
}

async function countArchivedTaskDirectories(root: string): Promise<number> {
  try {
    const months = await fs.readdir(root);
    let count = 0;
    for (const month of months) {
      const monthPath = path.join(root, month);
      const stat = await fs.stat(monthPath);
      if (!stat.isDirectory()) {
        continue;
      }
      count += await countImmediateVisibleDirectories(monthPath);
    }
    return count;
  } catch {
    return 0;
  }
}

async function collectTaskDirectories(tasksRoot: string): Promise<TrellisTaskDirectory[]> {
  const taskDirectories: TrellisTaskDirectory[] = [];

  try {
    const entries = await fs.readdir(tasksRoot);
    for (const entry of entries) {
      if (entry === 'archive') {
        continue;
      }
      const fullPath = path.join(tasksRoot, entry);
      const stat = await fs.stat(fullPath);
      if (stat.isDirectory()) {
        taskDirectories.push({ dirPath: fullPath, archived: false });
      }
    }
  } catch {
    // Ignore missing tasks root.
  }

  const archiveRoot = path.join(tasksRoot, 'archive');
  try {
    const months = await fs.readdir(archiveRoot);
    for (const month of months) {
      const monthPath = path.join(archiveRoot, month);
      const stat = await fs.stat(monthPath);
      if (!stat.isDirectory()) {
        continue;
      }
      const entries = await fs.readdir(monthPath);
      for (const entry of entries) {
        const fullPath = path.join(monthPath, entry);
        const entryStat = await fs.stat(fullPath);
        if (entryStat.isDirectory()) {
          taskDirectories.push({ dirPath: fullPath, archived: true });
        }
      }
    }
  } catch {
    // Ignore missing archive root.
  }

  return taskDirectories;
}
